### ISSUE TITLE
[SUGGESTION] Make user aware of guidelines for recording validation

### ISSUE THREAD

**Issue by rYR79435** [Sav22999/common-voice-android#100]
**Description feedback/suggestion**
In the discourse of Common Voice there are [guidelines](https://discourse.mozilla.org/t/discussion-of-new-guidelines-for-recording-validation/36465) for how to correctly validate recordings.
Show these or link to them when starting the app for the first time. Maybe also have a link to them somewhere else in the app.

It might even make sense to have them accessible in the recording validator. Users could then read them if they're unsure about their current recording.

**Comment by Sav22999** [comment]
@rYR79435 oh, I didn't know about these guidelines. In the Italian community we've done them at the beginning.

I can add a shortcut in Settings. Anyway, there is a first-run tutorial when you launch (the first time) Speak and Listen sections, and those first-runs are also translated.

Really thanks for the suggestion!

**Comment by SantosSi** [comment]
The validation rules do not seem to be very visible were they currently are. Can a link be shown on the recording and validation screen? 
Additionally the existing link leads to the english rules.

**Comment by Sav22999** [comment]
@SantosSi the link is always available on Settings > Useful links, and it's indicated in the first-run tutorial as well (the last screen of the tutorial)
