### ISSUE TITLE
F-Droid can't build - cleanup locales

### ISSUE THREAD

**Issue by licaon-kter** [Sav22999/common-voice-android#105]
https://f-droid.org/wiki/page/org.commonvoice.saverio/lastbuild_115

**Comment by Sav22999** [comment]
Oh, shit. Thanks. I've forgotten to update locales. Sorry

**Comment by licaon-kter** [comment]
If you delete tag & re tag, it will be retried next cycle.

**Comment by Sav22999** [comment]
Ok, I've just fixed and I've just pushed the 116 version code.

Please update me if it's fixed, and thanks again
