### ISSUE TITLE
[SUGGESTION] "save clips to device" option

### ISSUE THREAD

**Issue by Sobsz** [Sav22999/common-voice-android#107]
i know mozilla won't delete our clips, but personally i want to use them for other things anyway (such as making a text-to-speech engine) and since i'm recording them for common voice i might as well keep a copy for myself too

i understand this is a super-niche feature and i don't expect you to implement it (though it would be a nice surprise)

**Comment by Sav22999** [comment]
I think this is absolutely against Terms... you should accept other terms to download "Dataset".

**Comment by Sobsz** [comment]
nonono i mean only the clips recorded by the user who enabled the option
if i wanted other people's clips i'd just download the dataset like you said
i'm not a lawyer though so there might be some reason why the thing i'm proposing is not allowed

**Comment by Sav22999** [comment]
I don't know actually. I don't want to go againt Mozilla... in addiction it will be very difficult to manage, because the app should check also if there is enough space on disk, the directory, etc.

**Comment by Sav22999** [comment]
@Sobsz maybe you can try to ask to Mozilla on (Mozilla) Discourse (or if you have, on Mozilla Matrix > Common Voice), if they authorise me, I can try to put in "to-do list" here 😄

**Comment by Sobsz** [comment]
i actually did ask in the matrix room, two normal users said it's fine so ehhhhh
![Screenshot_2020-07-10-15-25-58-609_im vector riotx](https://user-images.githubusercontent.com/18291848/87159863-4aa51c00-c2c2-11ea-9515-e94b44513012.png)

**Comment by Sav22999** [comment]
@Sobsz yup, but I need an answer from lowyers... everyone can say "There's no problem" but it could not be true, can you understand?
Sorry if I'm a bit rude, but I don't want to give a pretext to ban this unofficial app.

**Comment by Sav22999** [comment]
@Sobsz would you save just your clips or also clips by others? Basically the question is: clips in "Speak" (yours) or in "Listen" (other people)?

**Comment by Sobsz** [comment]
just mine, if i wanted other people's clips i could simply download the dataset

**Comment by Sav22999** [comment]
Exactly. So there aren't legal issues because the audio is yours! I understood you wanted to download also other audios!

I approve this feature and I'll implement this in future 😄 

Reveal: probably you will need to turn on in Settings this feature and, for every clip, you will be able to download by pressing a "download" icon 😄; what do you think?

**Comment by Sobsz** [comment]
the ideal would be for it to save all the clips automatically (with the text as the filename or in a .txt file or similar) but i could probably get used to tapping an extra button every time

**Comment by Sav22999** [comment]
@Sobsz I'm happy to tell you this feature is implemented in the alpha release and, in the next stable release, there will be!

😄
