### ISSUE TITLE
[SUGGESTION] Open the guidelines to reviewing recordings when you first start validating records

### ISSUE THREAD

**Issue by J053Fabi0** [Sav22999/common-voice-android#112]
When someone is new to the app and they start reviewing audios, there should be a tutorial in which you can read [the guidelines for reviewing recordings](https://discourse.mozilla.org/t/discussion-of-new-guidelines-for-recording-validation/36465).

**Comment by Sav22999** [comment]
@J053Fabi0 There is a first-tutorial when you run, the first time, both Speak and Listen. In addition there is also a button, in Settings, which redirect you in that discussion

**Comment by J053Fabi0** [comment]
The first-tutorial doesn't talk about the guidelines, and the button is in Settings, so not the most accesible button for a user who is reviewing some clips. Maybe the button can be somewhere in the first-tutorial?

**Comment by Sav22999** [comment]
@J053Fabi0 I can add a dedicated page in first tutorial, sure. I'll add this

**Comment by Sav22999** [comment]
I'll close the issue when the feature will be in the stable release 😄

**Comment by Sav22999** [comment]
Added in Alpha version (2.1a -119)

**Comment by Sav22999** [comment]
Added in the new release (2.1).
I've published it just now :partying_face:
