### ISSUE TITLE
[SUGGESTION] Change the way of gradle dependency management 

### ISSUE THREAD

**Issue by bentleypark** [Sav22999/common-voice-android#115]
**Description feedback/suggestion**
There are two build.gradle in this project. But shared gradle dependencies in build.gradle are managed saparetly. 
I think it would be better to keep dependencies centralized and under control.  

**Draft expected**
[https://proandroiddev.com/gradle-dependency-management-with-kotlin-94eed4df9a28]([](https://proandroiddev.com/gradle-dependency-management-with-kotlin-94eed4df9a28))
Follwing the approach above link, It couble done easily. 
I want to contribute code if you are ok. 

**Additional context**

**Comment by Sav22999** [comment]
@bentleypark Hi! Really thanks.

Yup, if you want to do this, please do and then ask for the Pull Request. 😄

**Comment by bentleypark** [comment]
Thanks :)
