### ISSUE TITLE
[SUGGESTION] Apply viewbinding to reduce boilerplate code(findViewById). 

### ISSUE THREAD

**Issue by bentleypark** [Sav22999/common-voice-android#118]
**Description feedback/suggestion**
Using viewbinding, boilerplate code(ex. findViewById) can be replaced and code lines will be shorten. 

**Draft expected**

**Additional context**

**Comment by MrIndeciso** [comment]
Hi @bentleypark,
We already migrating to viewbinding in order to remove kotlin-android-extensions and findViewByID.
This is currently in its early stages, as you can see in my fork here https://github.com/MrIndeciso/common-voice-android, but we expect to merge the update before November.

**Comment by bentleypark** [comment]
Hi, @MrIndeciso. Thanks for your comment 😃
