### ISSUE TITLE
[SUGGESTION] Easier language switch

### ISSUE THREAD

**Issue by Masqueey** [Sav22999/common-voice-android#121]
**Description suggestion**
A drop-down menu on the main screen (not in settings) that only changes the language you are recording or validating in without changing the app's language.

**Draft expected**
Main screen:
- CV Android
- Hey, ...
  _Profile_
- Active language:
  _English_ v

**Additional context**
I love how easy it is to make and validate recordings in the app. However, since I am recording in three different languages, it sucks that I have to go to settings and change the entire app's language to change the language I'm recording in (which feels a bit unnecessary).

**Comment by Sav22999** [comment]
@Masqueey sorry for the delay. Basically in every app you change the language in the Settings.
In addition, for the "active language" it not easily to know.
Just, to avoid to add a feature that a few (or just one) people would use is not excellent practise (see the "KISS" principle).

If you really want to this feature I could advise you to fork this repo and add it yourself 😄 

I close this issue
