### ISSUE TITLE
[BUG] Loading a new language - grammar mistake

### ISSUE THREAD

**Issue by Masqueey** [Sav22999/common-voice-android#122]
_Android (OS) version:_ 10.0
_Android (OS) language (in English):_ English
_App release:_ 2.1 (119)
_App language (in English):_ English (but also in the translation in Dutch)
_Device RAM:_ 6GB
_Device display size (in Inches):_ ?
_From what store have you installed the app?:_ F-Droid
_Are there installed Google Services on your device?_ Yes

**Description bug**
When you change to a new language, the pop-up gives the message: "Language changed correctly to English." I believe this should be "Language successfully changed to English." or "Language successfully set to English."

**How to reproduce the bug**
1. Change the language of the app to English

**Additional context**
Correct is used when judging whether something was a mistake or not. "You have correctly understood my goal." / "You have misunderstood my goal." Successfully is used when describing the completion of an action.. "You have successfully completed all the goals." "You have successfully pressed the button." / "You failed to complete all the goals." "You were not able to press the button."

**Additional comment**
Sorry for correcting your grammar. (I will understand if you ignore this bug-report.) 
I really enjoy the app and I think by making one for Android you both raise awareness of the project and make it easier for people to join in.

**Comment by Sav22999** [comment]
@Masqueey That's absolutely correct. I'll use the form "Language successfully set to English" :smile: 

Thanks.
