### ISSUE TITLE
[BUG] Record is removed if the user wrongly swipe up and show the "Report" button

### ISSUE THREAD

**Issue by fcastagnotto** [Sav22999/common-voice-android#126]
_Android (OS) version:_ 6.0.1
_Android (OS) language (in English):_ Italian
_App release:_ 2.1 (119)
_App language (in English):_ English
_Device RAM:_ 2GB
_Device display size (in Inches):_ 5
(Optional, but recommended) _Device model (and brand):_ Motorola Moto G 3rd
_From what store have you installed the app?:_  Google Play Store
_Are there installed Google Services on your device?_ Yes

**Description bug**
After record a phrase, if the user wrongly swipe up and enable the "Report" popup, after click back to the record view, the record is deleted and it must be recorder again.

**How to reproduce the bug**
1. Go to "Record"
2. Record a phrase
3. Start the play of the recorded phrase
4. During the listening, swipe up the screen
5. On the popup of "report" click "Cancel"
6. Notice the disappeared play button

**Screenshots**

**Additional context**

**Comment by Sav22999** [comment]
@fcastagnotto Thanks for the report. This happens and we should fix this issue 😄
