### ISSUE TITLE
[SUGGESTION] Add social part

### ISSUE THREAD

**Issue by dag7dev** [Sav22999/common-voice-android#127]
**Description feedback/suggestion**
Based on a Tweet, it would be nice if when someone reaches its daily goal the app shows a pop-up saying something like "hey, you have reached your daily goal! Click here to share on twitter or facebook"

When user clicks on the target social the text should be like this: 

```
I have just reached my daily goal on CV Android. Join the army and help us to gather more voices, including yours!
Link: commonvoice.mozilla.org
<google play store link> #cvandroid #commonvoice #android 
```

**Comment by Sav22999** [comment]
I've just asked for an opinion in the Telegram group https://t.me/common_voice_android.

**Comment by Sav22999** [comment]
With 20 votes, 15 "Yes", 5 "No" and 0 "I don't know" this feature is approved!

I'll work it to implement this!

**Comment by Sav22999** [comment]
The text will be:

```
I've just achieved my daily goal using #cvandroid for @mozilla #commonvoice project.

Contribute also you via app! Install it from Google Play or F-Droid now https://bit.ly/2XhnO7h
```
