### ISSUE TITLE
[BUG] 2FA Github strange behaviour - forever loading

### ISSUE THREAD

**Issue by dag7dev** [Sav22999/common-voice-android#130]
_Android (OS) version:_ 10
_Android (OS) language (in English):_ Italian
_App release:_ 2.2b
_App language (in English):_ Italian
_Device RAM:_ ?
_Device display size (in Inches):_ ?
_From what store have you installed the app?:_  GitHub
_Are there installed Google Services on your device?_ Yes 

**Description bug**
When you try to login to Github with 2FA enabled, it asks for 2FA code.
Don't close the app (simply let that app be open in recent apps) and switch to your 2FA Manager - copy the code.
Return back to the app and...it will forever loading "something".
The only way to escape this is clicking "back" button, select login with Github again, input right credentials, click login, paste the 2FA code and click "ok". If you are fast enough it works but you can't expect a user to be so faster and input something twice xD

**How to reproduce the bug**
1. Open the app
2. Login with Github
3. It prompts to input 2FA Auth Code. Press "Home" button on your mobile phone.
4. Open 2FA Generator and copy the Github entry
5. Press "Recent Apps" button and return to CVApp. It will forever loading.

**Comment by Sav22999** [comment]
Fixed
