### ISSUE TITLE
[TRANSLATION] Lithuanian / Lietuvių

### ISSUE THREAD

**Issue by mjurkus** [Sav22999/common-voice-android#133]
_Language name in English:_ `Lithuanian`
_Language name (long, in the same native language):_ `Lietuvių`
_Language code in [Common Voice](https://commonvoice.mozilla.org/):_ `lt` -> The URL `https://commonvoice.mozilla.org/lt/`

**Comment by Sav22999** [comment]
@mjurkus thanks.
I've just added "Lithuanian" on Crowdin, so if you want to translate there. In max a week I should publish also a new release, so if you tranlate strings, it would be perfect.

https://crowdin.com/project/common-voice-android/lt

**Comment by mjurkus** [comment]
done

**Comment by Sav22999** [comment]
@mjurkus I've approved everything. Thanks 😄

**Comment by mjurkus** [comment]
@Sav22999 need help on something else to get to the release faster?

**Comment by Sav22999** [comment]
We are just testing the app, if you want to I can pass the Beta release to test (or you can download the Beta on Google Play). 😄
