### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Sav22999/common-voice-android#139]
Ref: https://f-droid.org/wiki/index.php?title=org.commonvoice.saverio/lastbuild_130&oldid=285859

Ref: https://gitlab.com/fdroid/fdroidserver/-/merge_requests/844

**Comment by licaon-kter** [comment]
Disable affected https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8201

**Comment by Sav22999** [comment]
@licaon-kter there's no Google Play Core library... it's a comment... comment are not executed

**Comment by Sav22999** [comment]
@MrIndeciso

**Comment by Sav22999** [comment]
@licaon-kter 
Sorry. I've just published a new release (131) and it doesn't have anymore those libraries.

Could you reactivate the Auto-Update on F-Droid, please?

**Comment by licaon-kter** [comment]
Grean
