### ISSUE TITLE
[BUG] Unable to load sound entries.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Sav22999/common-voice-android#14]
Despite being able to load French text entries for the voice recording, I can't seems to consult, and even less, be able to confirm the already submitted volunteers recordings.
The screen only shows the play button which doesn't react, a blank text box (...) and an error message, suggesting me to skip the entry, however, trying to skip multiple of those won't help.

**Comment by Sav22999** [comment]
This is very weird. Have you checked the Internet connection (mobile data or wifi) are actived? Now it doesn't show error box id there isn't connection.

**Comment by Sav22999** [comment]
@PoorPocketsMcNewHold in 0.0.15a release, this bug should be solved. Please, tell me

**Comment by Sav22999** [comment]
Because of no-answer I close this issue. If this bug still exists, I'll reopen it.
