### ISSUE TITLE
[BUG] Recorded clips are not uploaded to the CV server 

### ISSUE THREAD

**Issue by schirinowski** [Sav22999/common-voice-android#140]
##### About OS*

_OS version:_ 11

_OS language (in English):_ German

##### About the app (CV Android)*

_App release:_ 2.2.3 (build#131::FD-GH)  (2.2.2 (build#131::FD-GH) is also affected)

_App language (in **English**):_ German

##### About you device

_Device RAM:_ 6GB

_Device display size (in Inches):_ `5.8in`

_Device model (and brand):_ Samsung Galaxy S10e

_From what store have you installed the app?:_ GitHub

_Are there installed Google Services on your device?_ Yes

#### **Description bug** *

Recorded clips are not uploaded to the CV server. This applies to both anonymous and logged-in usage. Recording on the web site itself on the same device works flawlessly.

**Clip validation is not affected and works flawlessly.**

When recording in CV Android, the app-internal counter on the dashboard ("You") is incremented if logged in, but not the counter in the "top contributors" list (neither in the app nor on the CV web site).

#### **How to reproduce the bug** *

1. Log in to your CV profile in CV Android.
2. Visit statistics dashboard an remember the personal recording counter values in the "You" and "Top Contributors" sections.
3. Record a number of sentences in the app and send recordings to Common Voice server.
4. Visit statistics dashboard. Personal recording counters increased by the number of recordings made in the app, Top Contributors counter did not change.
5. Visit https://commonvoice.mozilla.org/de/dashboard/stats. The personal recording counters did not increase.

**How to check recordings were not sent to the server**
1. Open another "anonymous" CV Android instance **_without_** logging in (either on another device or in Android's work profile).
2. Make sure you are on the same language.
3. Validate available recordings until the app signals no more clips are available on the server for your language.
4. Visit https://commonvoice.mozilla.org/, **log in**, and record a couple of sentences.
5. Validate clips in the **anonymous** CV Android instance until the app signals no more clips are available on the server for your language. The sentences you just recorded will be among your validated clips.
6. Switch to your "personal" CV Android instance.
7. Record a couple of sentences and send them to the CV server.
8. Switch to the "anonymous" CV Android instance.
9. Validate clips until the app signals no more clips are available on the server for your language. The sentences you just recorded will **_NOT_** be among your validated clips.

##### **Expected Behaviour**
**A)** It should be like on my spare device:
* Nexus 7 (2013)
* Android 6.0.1
* CV Android 2.2.2 (build#131::FD-GH))

1. Follow steps 1.-3. as given above to reproduce the bug.
2. Visit statistics dashboard. Personal recording counters in the "You" and "Top Contributors" sections increased by the number of recordings made in the app.
3. Visit https://commonvoice.mozilla.org/. The personal recording counters increased correctly.

**B)** Recording on the web site itself on the same device works flawlessly. 
1. Visit https://commonvoice.mozilla.org/ and log in to your account.
2. Record a number of sentences.
3. Log in to your CV profile in CV Android.
4. Visit statistics dashboard. Personal recording counters in the "You" and "Top Contributors" sections increased by the number of recordings made on the web site.

#### **Screenshots**

![Screenshot_20210129-190204_CV Android](https://user-images.githubusercontent.com/47022976/106379510-d391bb00-63ac-11eb-87cc-a4ae6c8c8d62.jpg)
Initial counter values.

![Screenshot_20210129-190258_CV Android](https://user-images.githubusercontent.com/47022976/106379514-dbe9f600-63ac-11eb-9ca6-91bd40868441.jpg)
Additional recordings have been made.

![Screenshot_20210130-102827_CV Android](https://user-images.githubusercontent.com/47022976/106379524-e73d2180-63ac-11eb-824b-c54ae45c4d8f.jpg)
Even the next day, the top contributors list counter did not increase

#### Log file

~~Logging was not possible, see #141 for details.~~
No log was created, the app did not crash.

#### **Additional context**

Ideas:
* Samsung-specific?
I doubt. It worked for me before updating to Android 11.
* Related to Android 11?
Sounds reasonable, the app worked before updating to Android 11 on my S10e and still works on another device running Android 6.0.1. Possibly related to adjusted scoped storage handling (see https://medium.com/androiddevelopers/android-11-storage-faq-78cefea52b7c for the beginning). Would be sound, if CV Android works with temporary files for the recordings which are then uploaded. Don't know about the details, though. @Sav22999 should know.

**Comment by Sav22999** [comment]
@schirinowski Hi, thanks for the report.

Could you tell me more details please?

How do you know the recordings aren't uploaded?

**Comment by schirinowski** [comment]
Just briefly, need to get sleep 😅

1. Recording increments the app-internal counter, but not the counter in the top contributors list, neither in the app nor on the CV web site.
2. I installed CV Android in my work profile without logging in. Recordings made on the CV web site after logging in are offered in that app instance. Recordings with CV Android don't come up there, neither anonymous nor recordings after logging in.

Would love to send a log file, but the app doesn't write any. Permission to access storage is given (although it tells "access to media files" in the Android settings), logging activated. Is this related to Android 11 and a possible new bug?

**Comment by schirinowski** [comment]
Hi Saverio, I did another short test on a spare device:
* Nexus 7 (2013)
* Android 6.0.1
* CV Android 2.2.2 (build#131::FD-GH))

I logged into my account and recorded a couple of sentences. These got uploaded successfully, I was able to validate them in my "anonymous" CV Android instance. On top, the recorded counter in my account increased, also on the web site. Thus, it seems to be an Android 11 issue.

Apart from that, logging seems broken. No log file are created on that device, either. :-\

**Comment by schirinowski** [comment]
@Sav22999 I just augmented my initial description and deleted the other comments. Will elaborate on #141 later today or tomorrow.

**Comment by Sav22999** [comment]
@schirinowski the app saves recordings in a database, not as file.
Anyway, I'll try to check this issue, thanks again for the report.

Could you try another way, please?
1. Login on the website (commonvoice.mozilla.org), then login in the app (CV Android), with the same account.
2. In the website you should be able to see the number of recordings and validations, in the top-right (aside the username). Please, remember those numbers.
3. Now, in the app, try to validate or record something.
4. After this, go back in the website and refresh the page. Those numbers (so "contributions") are the same or have been they incremented?

**Comment by schirinowski** [comment]
Oh, sorry, that's a detail I did not mention: this was actually the way I realised there is something going wrong.
Results on the web site are:
* Recording counter remains same, not increased.
* Validation counter is increased.

**Comment by Sav22999** [comment]
@schirinowski ok, great!. Thanks.
I'll investigate to this bug

**Comment by schirinowski** [comment]
> @schirinowski the app saves recordings in a database, not as file.

@Sav22999 where is the DB stored? I could try to access it somehow.

**Comment by schirinowski** [comment]
@Sav22999 I just tried on another phone. It was factory-reset, having a fresh install of CV Android 2.2.3 (build#131::FD-GH). Same behaviour: recordings inside CV Android get not uploaded to the CV server, recordings on the same device made in the browser work flawlessly.

Phone details:
Sony Xperia X Dual (F5122), Android 8.0.0 (patch level: 1 September 2018)

Is there anything I can test for you?

**Comment by Sav22999** [comment]
Have you tried logged and unlogged?
Maybe is your account the issue? We can't understand what's the problem

**Comment by schirinowski** [comment]
I just tried it without logging in. Hence, the account shouldn't be the issue.

How can I debug further? The only thing I can do is capturing the network traffic.

**Comment by Sav22999** [comment]
Maybe you have a firewall...?

**Comment by schirinowski** [comment]
I... am... puzzled... Now it works! 🤷🥴
I first connected over cellular network, the counter increased. I then continued on WiFi, which I previously used when it didn't work. It continued working, the counter continued to increase with every recording.
I'll watch this further, I'm afraid it's not really solved.

**Comment by Sav22999** [comment]
@MrIndeciso what do you think?

**Comment by schirinowski** [comment]
Another test I did: I rebooted my phone yesterday and started CV Android right after connecting to my WiFi. It still worked fine.

**Comment by Sav22999** [comment]
@schirinowski this is very very weird 🤔 

Have you change Wi-Fi connection?
Maybe did you use the Wi-Fi at work-place? I don't really know what it could be 😕

**Comment by schirinowski** [comment]
Nope, nothing regarding that. Always the same WiFi at home, with unchanged configuration.

**Comment by Sav22999** [comment]
I don't know...
Anyway, because you don't have anymore this problem, I think I can close this issue now (in case we can reopen later).

What do you think?

**Comment by schirinowski** [comment]
Agreed, but still would appreciate to hear an opinion on this from your expert @MrIndeciso.

**Comment by MrIndeciso** [comment]
This is a pretty strange problem, and I don't have a clear idea about what's causing it.

At first I thought that it could have been related to Scoped Storage in Android 11, just as you said, but the usage of temporary internal files should still be allowed without requiring additional permissions.
Just to know, were you giving the app the Storage permission during the initial setup?

If it's not permission-related it might be caused by some kind of energy saving measure, as we use background workers to push and pull most of the data from the server.

Basically when you record a sentence it gets saved to a local temporary file (this is due to a limitation within the MediaRecorder API), then it is inserted as an entry into a DB table and the temporary file is flushed.
After saving it to the DB a chain of two background workers is enqueued. These two background workers only start processing the recorded sentences if the device has an active Internet connection, which is the only constraint.
The first worker is in charge of exporting the recorded clips as .mp3 files, but should instantly return if this option is not enabled in the settings menu, while the second takes every entry and tries uploading it to the CommonVoice server.
If the upload is successful the entry is deleted, if not a fail counter is increased and the background worker will try again after a set amount of time.

The points of failure in this flow should be the following:
-It might fail to save the temporary recorded file due to missing permissions
-If the option is enabled, the RecordingsExportWorker might fail due to missing permissions
-CommonVoice servers might be having some issues
-The background worker is never started because Android thinks that the Connection.ACTIVE constraint is not met
-The first backgrounds worker doesn't return even if it should
-The background worker is never started because some energy saving measure is preventing it from doing potentially CPU intensive work

Either I'm missing something or your problem should fall inside one of these six cases, but I can't see how, as experiencing the same behaviour on two different devices with different API versions excludes most of them.

Anyway, if it got fixed by itself I guess we will never know.

If it happens again it might be useful to look into the application logs to check the results of the various background workers, but I'm afraid that you need a debuggable APK for it.

**Comment by schirinowski** [comment]
@MrIndeciso, Thank you for your elaborated answer and insights to how the internal process is.

Before I wanted to answer, I did some further tests. Indeed, there are no further issues recording and uploading clips. All recordings counted so far, regardless of the network I am on.

Let's look into the possible points of failure:
> The points of failure in this flow should be the following:
> -It might fail to save the temporary recorded file due to missing permissions

I'll cross this one out as the app log was stored successfully in the end

> -If the option is enabled, the RecordingsExportWorker might fail due to missing permissions

I never enabled this. The only thing I changed on the spare device was disabling offline mode, as I thought it might be something related to this. The rest were initial configuration values. And write permissions were given during the first start of the app.

> -CommonVoice servers might be having some issues

Might be, hard to say. Wouldn't have affected the web site, though.

> -The background worker is never started because Android thinks that the Connection.ACTIVE constraint is not met

Wouldn't this affect validating clips as well? And this works.

> -The first backgrounds worker doesn't return even if it should

Can't imagine, as the export is not configured to happen.

> -The background worker is never started because some energy saving measure is preventing it from doing potentially CPU intensive work

Can't imagine, as the factory-reset spare device should not have anything so massively running in the background. No other app was installed on it.
 
> If it happens again it might be useful to look into the application logs to check the results of the various background workers, but I'm afraid that you need a debuggable APK for it.

No problem for me. ;-) If there is anything I can see from Logcat, just let me know and I'll give it a try.

Anyway, I'll watch this for some more time and see whether it comes up again - or not. 😁

**Comment by jwmh** [comment]
Follow-up comment:
I am seeing dozens of very old *.mp3 files,
 of my own voice,
 in 
/sdcard/Download/cv-project/

... going back several months (multiple dates and multiple months, including up thru a few days ago).

I use an anonymous (stock comes with this app) built-in account.
(I never created my own.)

I use offline mode primarily...
How can i check if the recordings were uploaded to mozilla, or not??

**Comment by Sav22999** [comment]
@jwmh you can see if the counter on my website is increased.
See it here https://www.saveriomorelli.com/commonvoice/app-usage/user/
