### ISSUE TITLE
[BUG] Logging does not output a log file

### ISSUE THREAD

**Issue by schirinowski** [Sav22999/common-voice-android#141]
##### About OS*

_OS version:_ 11/6.0.1

OS language (in English):_ German

##### About the app (CV Android)*

_App release:_ (e.g. `2.2 (#125::GPS)`) -> you can find it in `Settings`, center-bottom position

_App language (in **English**):_ (e.g. `Italian`)

##### About you device

_Device RAM:_ (e.g. `2GB`) -> you can write `?` if you don't know it

_Device display size (in Inches):_ (e.g. `5.9in`) -> you can write `?` if you don't know it

(**Optional**, but recommended) _Device model (and brand):_ (e.g. `LG G6 H870`)

_From what store have you installed the app?:_  F-Droid / Google Play Store / GitHub / Huawei AppGallery / Other (specify!)

_Are there installed Google Services on your device?_ Yes / No (specify if you have *Amazon Services* or *Huawei Services*, or other)

#### **How to reproduce the bug** *

1. Go to _Example_
2. ...

#### Log file

You can find the log file in the `Internal storage` > `Android` >  `data` > `org.commonvoice.saverio` > `files` > `logs` > `log.txt`

**Comment by bentleypark** [comment]
@schirinowski Hi, thanks for the report. 
The log file would generate right after app have crahshed . 
When you checked out log file, did app crashed?

**Comment by schirinowski** [comment]
@bentleypark, I think we can close the issue. I misunderstood that the log file contains kind of a trace log of what has been executed in the app. The app doesn't crash with respect to #140. Now I understand that no log file will be written in this case.

Second, I saw that a log actually was created tonight. So all seems to work as expected.

Please excuse for creating the confusion.

**Comment by Sav22999** [comment]
@schirinowski no problem 😄
