### ISSUE TITLE
[TRANSLATION] Slovak

### ISSUE THREAD

**Issue by Myno113** [Sav22999/common-voice-android#142]
_Language name in English:_ Slovak
_Language name (long, in the same native language):_ Slovenčina
_Language code in [Common Voice](https://commonvoice.mozilla.org/):_ sk -> The URL `https://commonvoice.mozilla.org/sk/`

**Comment by Sav22999** [comment]
@Myno113 the CV Android is already translated in Slovak: https://crowdin.com/project/common-voice-android/sk#

**Comment by Myno113** [comment]
Yes, you are right, just finished some translations today. Even the language exists on Crowdin and Mozilla Common Voice I still don't see it available in the CV Android app.

**Comment by Sav22999** [comment]
@Myno113 Sure. I've just approved all translations. Those translations will be available in the next release, it's not in real time, sorry

**Comment by Myno113** [comment]
Thank you. Looking forward to see it in the next release :smiley: 
BTW thanks for such a great app!

**Comment by Sav22999** [comment]
@Myno113 it's a pleasure!
