### ISSUE TITLE
[SUGGESTION] Can you add galician

### ISSUE THREAD

**Issue by meixome** [Sav22999/common-voice-android#143]
**Description feedback/suggestion**

Hi,
I have download the app. Seems magnificient!
I'm promotor for galician common voice community. We are feeding the sentence collector and we can be ready for production.
Can you add galician as language option as for contributing to?

I will made the galician translation for this app.

**Draft expected**
If you want to send a mock-up, or just a drawing, of your idea.

**Additional context**

**Comment by Sav22999** [comment]
I close this issue because there's the correct one #144 about translation
