### ISSUE TITLE
[TRANSLATION] Galician

### ISSUE THREAD

**Issue by meixome** [Sav22999/common-voice-android#144]
_Language name in English: `Galician`
_Language name (long, in the same native language): `Galego`
_Language code in [Common Voice](https://commonvoice.mozilla.org/):`gl` 
`https://commonvoice.mozilla.org/gl`

**Comment by Sav22999** [comment]
@meixome I've just added the language on Crowdin https://crowdin.com/project/common-voice-android/gl
