### ISSUE TITLE
[SUGGESTION] Add Slovak language

### ISSUE THREAD

**Issue by Myno113** [Sav22999/common-voice-android#148]
**Description feedback/suggestion**
Please add "Slovak" language in the language list.
Thank you.

**Draft expected**

**Additional context**

**Comment by Sav22999** [comment]
Hi! Slovak is already in the language list.

Could you tell me your app version?

**Comment by Myno113** [comment]
Ah, I thought I have installed the latest (2.3) version, but had 2.2.2 instead.
Sorry for confusion, Slovak language appeared in the list right after I updated to the version 2.3 :smile:
Thanks for checking this so fast!

**Comment by Sav22999** [comment]
@Myno113 No problem!

Enjoy with the app 😄 and remember to review it, if you want to 😄
