### ISSUE TITLE
[BUG] Does noz show german as the language I switched to in the prompt that comes up whrn I switch

### ISSUE THREAD

**Issue by mxrixs** [Sav22999/common-voice-android#149]
#### General information

After switching language a prompt comes up that is probably suppoest to say "Langauge changed successfully to WHATEVERLANGUAGE" in the respective lamguage. After switching to german it showed "{{+{lang}+}}" Instead (replace "+" with "*" because two stars cause formatting in github)

##### About OS*

_OS version:_

Android 10
Oxygen OS 10.0.11.GM22BA

_OS language (in English):_

German

##### About the app (CV Android)*

_App release:_ 

2.3(build#134::GPS)

_App language (in **English**):_

now German, before seitching anything else

##### About you device

_Device RAM:_

8gb

_Device display size (in Inches):_

6.67"

_Device model (and brand):_ 

OnePlus 7 pro

_From what store have you installed the app?:_

Google Play Store

_Are there installed Google Services on your device?_

Yes

#### **Description bug** *

After switching language a prompt comes up that is probably suppoest to say "Langauge changed successfully to WHATEVERLANGUAGE" in the respective lamguage. After switching to german it showed "{{*{lang}*}}" Instead

#### **How to reproduce the bug** *

1. Go to Settings
2. change language to anything besides German or "Deutsch"
3. Switch bsck to German
4. click "ok" on the "Info" prompt, if enabled

#### **Screenshots**

![Screenshot_20210310-155423](https://user-images.githubusercontent.com/64852250/110649938-6139a500-81ba-11eb-8856-3042ded7fa05.jpg)

German text can be translated literally to "Language sucessfully to THEBUG changed". (It is gramatically correct)

#### Log file

You can find the log file in the `Internal storage` > `Android` >  `data` > `org.commonvoice.saverio` > `files` > `logs` > `log.txt`

**Comment by Sav22999** [comment]
@mxrixs thank you, I'll fix this issue with the strings.
Sorry for the inconvenience
