### ISSUE TITLE
[BUG] CV Android screenshots and banners on the app stores

### ISSUE THREAD

**Issue by schirinowski** [Sav22999/common-voice-android#151]
Hi @Sav22999, as of now there are still the CV Android banners and screenshots (especially the first one from the live app) on the app stores, whereas the description has been changed to CV Project. That should be aligned.
Best!

**Comment by Sav22999** [comment]
@schirinowski I've updated all screenshots as well. Where did you find the old screenshots?

**Comment by Sav22999** [comment]
Ok, I've understood now. You mean in the first screenshot (and the second one) there is "CV Android" inside the image?

You're right, I'll update it later. Thanks!

**Comment by schirinowski** [comment]
> You mean in the first screenshot (and the second one) there is "CV Android" inside the image?

Exactly! 😉👍
