### ISSUE TITLE
[BUG] F-Droid: no version with valid signature available

### ISSUE THREAD

**Issue by schirinowski** [Sav22999/common-voice-android#152]
#### General information
I can't update to CV Project from the F-Droid store. It just shows me "no version with valid signature available". 

##### About OS*

_OS version:_ 11

_OS language (in English):_ German

##### About the app (CV Android)*

_App release:_ 2.2.3 (build#131::FD-GH)

_App language (in **English**):_ German

##### About you device

_Device RAM:_ 6GB

_Device display size (in Inches):_ `5.8in`

_Device model (and brand):_ Samsung Galaxy S10e

_From what store have you installed the app?:_ GitHub

_Are there installed Google Services on your device?_ Yes

Any ideas? Is that expected for my setup?

**Comment by Sav22999** [comment]
Try to install from F-Droid instead of GitHub 😀

**Comment by schirinowski** [comment]
Uh, damn, I thought I still was on F-Droid. 🙈 Must face switched to GitHub while bug-hunting.

Fresh install from F-Droid solved it. Thanks!
