### ISSUE TITLE
Irish language translation

### ISSUE THREAD

**Issue by seananocoistin** [Sav22999/common-voice-android#165]
Hello, I would like to translate the CV Project into the Irish language.

**Comment by Sav22999** [comment]
Yes, please tell me the Irish code (I mean "commonvoice.mozilla.org/{language_code}")

**Comment by seananocoistin** [comment]
Ciao,

Irish uses the code ga or ga-IE.

https://commonvoice.mozilla.org/ga-IE

Regards,

Seanán Ó Coistín


Ar 03/05/2021 22:41, scríobh Saverio Morelli:

**Comment by Sav22999** [comment]
@seananocoistin I've added it on Crowdin 😄 you can now translate. Enjoy with translation
