### ISSUE TITLE
[SUGGESTION] Prevent skip during voice recording

### ISSUE THREAD

**Issue by fabpolli** [Sav22999/common-voice-android#166]
**Description feedback/suggestion**
When phrase is during review if button "skip" is pressed a warning will be presented to the user to prevent losing of recorded file.
When recording is in progress no warn appear if the button is pressed accidentaly

**Draft expected**
Same behavior during registration, consistent with the behavior of the review phase

**Comment by Sav22999** [comment]
Yes, I think this could be a good idea.
Thank you 😄
