### ISSUE TITLE
[SUGGESTION] Add also the sentence-id / clip-id for "app-usage statistics"

### ISSUE THREAD

**Issue by Sav22999** [Sav22999/common-voice-android#168]
**Description feedback/suggestion**
Someone suggested to add also the sentence-id / clip-id for "app-usage statistics" on my webserver

**Draft expected**
If you want to send a mock-up, or just a drawing, of your idea.

**Additional context**

**Comment by ftyers** [comment]
Basically stuff like:
* Reported sentences (and why)
* Which sentences have been recorded
