### ISSUE TITLE
[SUGGESTION] Add option to review sentences from sentence collector

### ISSUE THREAD

**Issue by Fooftilly** [Sav22999/common-voice-android#172]
**Description feedback/suggestion**
It would be really nice if you could also use [sentence collector](https://commonvoice.mozilla.org/sentence-collector) tools inside this app too. I don't expect the feature where you add them, but the review option only. 

I envisioned it in the same way as the voice review. You wouldn't have the play button, but only thump up/thump down that we now have. When I first started contributing to CommonVoice I wasn't even aware that there is sentence collection. It isn't easily discoverable on the main site, and adding it to this app would be useful for reaching more people. Also, offline reviewing would be highly appreciated because it doesn't use much space, and downloading like 5000 sentences would be less than 1MB.

**Comment by Sav22999** [comment]
@Fooftilly thanks for the feedback.
The account is different (login) is different.
In addition, I've in my plain to create an app dedicated to the Sentence Collector (https://github.com/cv-project-app/cvp-sentence-collector), but for now I don't have enough time, sorry

😄
