### ISSUE TITLE
[SUGGESTION] Add mode to upload only on WiFi

### ISSUE THREAD

**Issue by ftyers** [Sav22999/common-voice-android#176]
For people with expensive mobile data, it would be useful to have a mode like the offline mode, where it basically only uploads if on WiFi and if on mobile data operates in offline mode.

**Comment by jwmh** [comment]
Seconded!
Also an upload LOG would be very helpful, to confirm it is actually uploaded successful...

**Comment by Sav22999** [comment]
@jwmh the log is already present and if there is some errors the app try again later (and send the error log to my website and save it on device, is it's enabled in Settings)

**Comment by Sav22999** [comment]
See version 2.5
