### ISSUE TITLE
[SUGGESTION] Add possibility to check someone's all uploads in a row

### ISSUE THREAD

**Issue by Fehertukor** [Sav22999/common-voice-android#177]
Hi! Thank you for your work!

I want to help with validation more and more!
There are some people whose records are much more clear and easier to understand
 I wish to validate all of their works in a row if it is possible. This would help me tremendously!

For example hear somebody's work and a + one button from him/her or an infinite symbol to always give their work until you checked it all.(of course without names if necessary).

**Comment by Sav22999** [comment]
It's not possible get sentences recorded (so clips) of a specific users, I'm sorry. The Mozilla API doesn't permit this (basically with the clip, you cannot know the user who recorded the sentence. This is to protect the privacy)

**Comment by Fehertukor** [comment]
Thanks! I understand.
