### ISSUE TITLE
[SUGGESTION] less scrolling - better use of screen space

### ISSUE THREAD

**Issue by Matthias84** [Sav22999/common-voice-android#178]
**Description feedback/suggestion**

I appreciate the app and use it  a lot to contribute my voice. But while my Sony H3213 has a 6" display, the app doesn't show all the elements, esp. in recording mode:
![Screenshot_20210628-183845_Trebuchet](https://user-images.githubusercontent.com/217511/123673011-3f832d00-d840-11eb-9a47-e3f201fb9612.png)

![Screenshot_20210628-183920_Trebuchet](https://user-images.githubusercontent.com/217511/123673206-7bb68d80-d840-11eb-8872-ba67cc3ec464.png)

**Draft expected**
I recommend to put the recording and playback buttons on the same level. Maybe it's also useful to add similar buttons with icons for the transmission, skip and reporting functions, to save space?
I'm not sure about the context help text, how this can be improved. Maybe an semi-transparent overlay like a tooltiptext on the lyrics textblock?

**Additional context**

**Comment by Sav22999** [comment]
@Matthias84 Thanks for the report. I'm working to a better solution, and I would like creating a screen like "Listen" (so two buttons aside the main, one to playback/rerecord, and another to send).

Could you send a screenshot of the Listen section, so I can see if it's shown correctly?
In addition, I can't understand why the "guide sentences" are behind the button :thinking: what version of the app do you use?

**Comment by Sav22999** [comment]
What di you think about this idea?

![Screenshot_20210628-224922](https://user-images.githubusercontent.com/32335378/123702388-5a1acd80-d863-11eb-8895-b9e0a826f1ea.png)
![Screenshot_20210628-224633](https://user-images.githubusercontent.com/32335378/123702393-5b4bfa80-d863-11eb-8c1e-82fadc5eddc8.png)

**Comment by Matthias84** [comment]
Looks good to me :+1:  Maybe it's a better to move the most important buttons (Play rec skip) down, so it's easier to reach them via your thumb, if you use your phone in a single hand?

P.S: Would a skip icon like on a hifirack make sense? ([android skip next](https://fonts.google.com/icons?selected=Material+Icons:arrow_upward&icon.query=arro))

**Comment by Sav22999** [comment]
I used the same layout of Listen, so it should be more easier use the app.

The is already a "skip" icon in the app, if you use the gestures you can see it
