### ISSUE TITLE
[SUGGESTION] Linebreaks using Hyphenation

### ISSUE THREAD

**Issue by Matthias84** [Sav22999/common-voice-android#179]
**Description feedback/suggestion**
Currently the app adds linebreaks within the textsamples just by string length. This makes it sometimes hard to speak, as it doesn't break naturally and you need to think to much. This effect is esp. true in languages like german with a lot of long (composed) words.
![Screenshot_20210629-194834_Trebuchet](https://user-images.githubusercontent.com/217511/123864940-9a458300-d92b-11eb-9a7e-8f13fbe6295f.png)
(It would be 'Hand- werkerfamilie' or a full line for the word)

**Draft expected**
Make use of a (NLP?) library which can split words on the right syllables and add a '-' to indicate its just a break and the word continues.

**Additional context**

**Comment by Sav22999** [comment]
I actually think it's an issue with the translated string. You can correct them on Crowdin :)

The app use the "auto wrap" of Android, so the word(s) go to a new line when the space finishes, but the word(s) is not "cut".

**Comment by Sav22999** [comment]
@Matthias84 Oh, probably I've misunderstood.
Did you mean the sentence to validate is "wrong"? In that case, use the feature "Report" because it's a problem with the sentence. The app just show it, and the app uses the "auto-wrap", as I said, which doesn't cut any sentences

**Comment by Matthias84** [comment]
Hi, no the sentence itself is perfectly fine :wink:  but the way how a word is split to match the textbox. My suggestion is to implement a splitting in a way that is language depended. For the example above, this might be:
> Ludwig Gottsleben
> entstammt einer
> bürgerlichen Hand-
> werkerfamilie

This is how newspapers etc. would print the text, if there is limited space in layouts (see [hyphen](https://en.wikipedia.org/wiki/Hyphen)).

Is this "auto wrap" feature be limited to Google Android? (I use linageos custom rom instead)

**Comment by Sav22999** [comment]
@Matthias84 Auto wrap is the default way, used bu everyone. Also on the Mozilla website sentences are shown in this way :D

Anyway, thanks, I’ll think about this suggestion for the future

**Comment by Sav22999** [comment]
@Matthias84 I didn't see your the example. I think it cuts the words because the word was "too long" for the display size :/

Have you tried to reduce the text-size in Settings? :D
