### ISSUE TITLE
Fdroid : CV project broken link

### ISSUE THREAD

**Issue by Rebecca-du-58** [Sav22999/common-voice-android#183]
##### About OS*

_OS version:_ `9.0`

OS language (in English):_  `French`

##### About the app (CV Project)*

_App release:_  `2.3.4` -> you can find it in `Settings`, center-bottom position

 `From Fdroid`

_App language (in **English**):_  `English`

##### About you device

_Device RAM:_  `4GB` -> you can write `?` if you don't know it

_Device display size (in Inches):_ `?`

(**Optional**, but recommended) _Device model (and brand):_  `Huawei P20 Lite`

_From what store have you installed the app?:_  F-Droid / Google Play Store / GitHub / Huawei AppGallery / Other (specify!) `Fdroid`

_Are there installed Google Services on your device?_ `Yes` / No (specify if you have *Amazon Services* or *Huawei Services*, or other) `I have Huawei service on it.`

#### **Description bug** *

 `I can't install the app on my phone.`

#### **How to reproduce the bug** *

 `try to install it today. The link is just broken.`

#### **Screenshots**

![Screenshot_20210910_083427_org fdroid fdroid](https://user-images.githubusercontent.com/47145972/132810394-960a5fd0-f469-4da7-a7ce-208db3de35d0.jpg)

#### Log file

You can find the log file in the `Internal storage` > `Android` >  `data` > `org.commonvoice.saverio` > `files` > `logs` > `log.txt`

**Comment by Sav22999** [comment]
Hi, I'm sorry for the bug.

Why are you installing the 2.3.4 release? The latest one on F-Droid is the 2.3.8

I don't know why the 2.3.4 is not installable 🤔 try to install it from the apk you find here on GitHub in "release"

**Comment by Rebecca-du-58** [comment]
Good morning,Thank you for your reply. Actually I managed to download the right version. It didn't work before because the store wasn't updated. I think it was the problem because I had to close it and open it again after the update. Now it's working!Thank youRebecca-------- Message original --------De : Saverio Morelli ***@***.***>Date : ven. 10 sept. 2021 à 09:23À : Sav22999/common-voice-android ***@***.***>Cc : "Rebecca O." ***@***.***>, Author ***@***.***>Objet : Re: [Sav22999/common-voice-android] Fdroid : CV project broken link (#183)

Hi, I'm sorry for the bug.

Why are you installing the 2.3.4 release? The latest one on F-Droid is the 2.3.8

I don't know why the 2.3.4 is not installable 🤔 try to install it from the apk you find here on GitHub in "release"
