### ISSUE TITLE
[TRANSLATION] Thai Language

### ISSUE THREAD

**Issue by ppnplus** [Sav22999/common-voice-android#197]
_Language name in English:_ Thai
_Language name (long, in the same native language):_ ไทย
_Language code in [Common Voice](https://commonvoice.mozilla.org/):_ (e.g. `it`, `fr`, `sv-SE`, ...) [th](https://commonvoice.mozilla.org/th)

**Comment by Sav22999** [comment]
@ppnplus Hi, "th" is already present in the app 😄
