### ISSUE TITLE
[BUG] Italian doesn't show texts to validate

### ISSUE THREAD

**Issue by riveravaldez** [Sav22999/common-voice-android#198]
##### About OS*

LineageOS 17.1-20220211-NIGHTLY-surnia (Android 10)

OS language (in English): English

##### About the app (CV Project)*

_App release:_ `2.4.0.5 (#179::FD-GH)`

_App language (in **English**):_ `Italian`

##### About your device

_Device RAM:_ `1GB`

_Device display size (in Inches):_ `?`

_Device model (and brand):_ `Moto E LTE T03970LI5J (lineage_surnia-userdebug 10 QQ3A.200805.001 10039282)`

_From what store have you installed the app?:_  F-Droid

_Are there installed Google Services on your device?_ No

#### **Description bug** *

Try to listen to validate: doesn't show texts and says,

 > _Il server API Common Voice non ha fornito altri clip. Prova più tardi o contatta Mozilla._ 

#### **Screenshots**

![Screenshot_20220703-172137_CV_Project](https://user-images.githubusercontent.com/1629138/177056515-c06ced75-d3a7-492b-8fc6-f1aee8a3b956.png)

**Comment by Sav22999** [comment]
@riveravaldez probably in Italian are finished clips available for validating... try to record sentences instead 😉

**Comment by Sav22999** [comment]
@riveravaldez are you using "Offline mode" and, in case, a value greater than 50?
Probably that's the problem... I'm looking for a soluting

**Comment by Sav22999** [comment]
See version 2.5

**Comment by riveravaldez** [comment]
> See version 2.5

Thanks!, I'm gonna check it and report if necessary.

And sorry for the delay... Thanks again. Regards!
