### ISSUE TITLE
[TRANSLATION] Sardinian

### ISSUE THREAD

**Issue by asereze** [Sav22999/common-voice-android#200]
_Language name in English:_ Sardinian
_Language name (long, in the same native language):_ Sardu
_Language code in [Common Voice](https://commonvoice.mozilla.org/):_`sc` -> https://commonvoice.mozilla.org/sc/

All the strings have been translated already on Crowdin for a while (I forgot to open the issue here).
Could you please add it to the list of languages?

**Comment by Sav22999** [comment]
@asereze Hi, I know. I'll update the app in some weeks maximum with some changes 

Sorry for the late.
If I don't wrong, I should be already enable the Sardinian in the app (not the translation, but the choose of language), don't you find it?

**Comment by asereze** [comment]
@Sav22999 Yes, sorry, I didn't make myself clear in the message. I meant the list of translated languages (I thought that was the issue), as you said the app is already enabled for Sardinian contributions. I've been using it for a while.

**Comment by Sav22999** [comment]
See version 2.5
