### ISSUE TITLE
[BUG] Signature of APK for 0.0.20 is broken

### ISSUE THREAD

**Issue by IzzySoft** [Sav22999/common-voice-android#25]
**Description bug**

The APK attached to release 0.0.20 has a broken signature. Could you please check, resign and re-attach?

**How to reproduce the bug**

run `apksigner verify -v *.apk` and see the output.

**Additional context**

```
DOES NOT VERIFY
ERROR: No JAR signatures
ERROR: org.commonvoice.saverio_0.0.20.apk: 
ERROR: Old APK signature failed to verify: org.commonvoice.saverio_0.0.20.apk
```

**Comment by Sav22999** [comment]
@IzzySoft I've just updated release 0.0.20b apk, tell me if it's incorrect again, I'm so sorry for the issue

**Comment by IzzySoft** [comment]
Thanks for the fast response, @Sav22999 – I can confirm all is fine now! Update will show up in my repo with tomorrow's sync. And no worries, things happen; luckily my updater immediately reports to me, so I can raise an issue, and things get fixed before someone else notices :smile:
