### ISSUE TITLE
[TRANSLATION] Russian

### ISSUE THREAD

**Issue by komachi** [Sav22999/common-voice-android#31]
_Language name in English:_ Russian
_Language name (long):_ Русский
_Language code in Common Voice:_ ru
_Language code in [Android Studio](https://android.googlesource.com/platform/frameworks/base/+/android-9.0.0_r1/core/res/res/values/locale_config.xml):_ ru-RU

**Comment by Sav22999** [comment]
@komachi thank you. You can translate the app in Russian, choose your language and go 😄  https://crowdin.com/project/common-voice-android

**Comment by komachi** [comment]
Done.

**Comment by Sav22999** [comment]
Perfect. Thank you very much.
I'll update the app in some days 😄

**Comment by Sav22999** [comment]
@komachi 0.2.5b released! Thanks again. I close this issue
