### ISSUE TITLE
[CRASH] Crash after selecting language

### ISSUE THREAD

**Issue by Jomosoto** [Sav22999/common-voice-android#32]
_Android (OS) version:_ 6.0.1
_Android (OS) language:_ German
_App release:_ 0.2.2b
_Device RAM:_ 2,8GB
_Display size:_ 5,2in
_Device model:_ Blackberry DTEK50 (STH100-2)
_From what store have you installed the app?:_ F-Droid
_Are there installed Google Services on your device?_ Yes

**Description**

After I permitted the access to my microphone and the storage I had to select my language. When I hit finish, the App crashes (I get the "... has stopped" message). When I try to restart it, it crashes again immediately.

**How to reproduce the bug**
1. Select any language
2. Hit finish

**Screenshots**
![Screenshot_20200312-220718](https://user-images.githubusercontent.com/40580158/76566851-f0c84d00-64ad-11ea-9ebd-1c995ba22ec5.png)

![Screenshot_20200312-220636](https://user-images.githubusercontent.com/40580158/76566947-1c4b3780-64ae-11ea-8598-b5c7cebcf523.png)

**Comment by Sav22999** [comment]
@Jomosoto  Please, translate me in English the (error) message

**Comment by Jomosoto** [comment]
"Unfortunately common Voice has stopped"

**Comment by Sav22999** [comment]
Ok, perfect. Thanks. I will check this bug. In addition, I want to inform you that the app is at 0.2.5b (I don't know why f-droid didn't updated the app)

**Comment by Sav22999** [comment]
@Jomosoto I've fixed this bug. I've released 0.2.6b. You can install just now directly via Github.
Thanks for the report and enjoy with the app! 😄
