### ISSUE TITLE
[SUGGESTION] Add option to set a "daily goal" (not official, just for the app)

### ISSUE THREAD

**Issue by Sav22999** [Sav22999/common-voice-android#35]
**Description feedback/suggestion**
Add "Daily goal" in "Dashboard".
You should can do:
- Add a new goal (choose from some default goals)
- Remove the goal, if don't you want anymore

**Draft expected**
In the Dashboard section:
![immagine](https://user-images.githubusercontent.com/32335378/76624595-df2a8800-6535-11ea-8549-e760a13af1fe.png)
Daily goal activity (Set now/Edit goal):
![immagine](https://user-images.githubusercontent.com/32335378/76626060-bd7ed000-6538-11ea-864d-c98042ae3382.png)
In the Dashboard section - Daily goal is set, and user achived the goal (today):
![immagine](https://user-images.githubusercontent.com/32335378/76626366-56ade680-6539-11ea-99bf-b66f75d70f48.png)
In the Dashboard section - Daily goal is set, but user didn't achive the goal (today):
![immagine](https://user-images.githubusercontent.com/32335378/76626444-77763c00-6539-11ea-8f33-dde043de8f9f.png)

**Additional context**
In the "Daily goal activity" should be more details, like "Setting the daily goal, you should reach `{{*{{n_selected}}*}}` clips validated and `{{*{{n_selected}}*}}` sentences recorded every day.

**Comment by xnumad** [comment]
Such feature with more options is already official (**account necessary**):
https://voice.mozilla.org/en/dashboard/goals
Using data from that one instead of an app-only goal would make it coherent with the website.

**Comment by Sav22999** [comment]
@xnumad I know, but it doesn't work very well. For example, you cannot delete a goal. In addition, goal is different for every language. I think it's a bit busy and "messy" :smile: .
