### ISSUE TITLE
[BUG] Unable to load a clip to listen

### ISSUE THREAD

**Issue by Booteille** [Sav22999/common-voice-android#36]
Hi. When using the app, I get an error saying there is no more clip to listen in the selected language (French) but there are still a bunch of clips when using the website of common voice.

**Comment by Sav22999** [comment]
Hi! What version do you use?

**Comment by Sav22999** [comment]
@Booteille I mean, what's the version of the *app* you are using? Because I should have fixed that bug in a past release.

In particular, please on the website https://voice.mozilla.org, after you logged-in there, check if you "checked-on" the "Privacy policy" in your Account (and remember to click "Save").
It should be/appears like this, after the procedure:
![immagine](https://user-images.githubusercontent.com/32335378/77761024-a14e5900-7037-11ea-9566-ffd79483a3e8.png)

**Comment by Booteille** [comment]
I am using the version available on f-droid, 0.2.2b, so I guess it's outdated!

**Comment by Sav22999** [comment]
@Booteille Yes, it's outdated. I've just contacted F-droid to know why the app is not updated... there was and error. I think that in some days should arrive the new version :) and that bug should be solved. But, anyway, you have to accept "Privacy policy" on https://voice.mozilla.org

**Comment by Booteille** [comment]
Okay, thanks! I'll be waiting for the f-roid version then.

I have no such an option on my account. I'll wait for the f-droid update and try again anyway. I'll keep you in touch.

**Comment by Sav22999** [comment]
@Booteille I've just seen that now, on F-droid, there is a newer version. Please, tell me if the bug is fixed

**Comment by mrwesleycrusher** [comment]
Hello!
I just downloaded the version 2.9B from F-Droid, and when I try to sign in with firefox it authenticates fine, but on the next screen it crashes. I am running Android 10 on a Galaxy S9. I assume its related to me not accepting the privacy policy. I will go accept it on desktop and let you know if that fixes it

**Comment by mrwesleycrusher** [comment]
That fixed it! So it might be worthwhile that until the bug is fixed to put that in the README on the front page/ in the app's description.

Anyways! Thanks for making this app!

**Comment by Sav22999** [comment]
@mrwesleycrusher so, it went to crash until you read the Privacy policy?

**Comment by mrwesleycrusher** [comment]
Yes.

**Comment by Sav22999** [comment]
@mrwesleycrusher oh, thanks. I thought it was managed ... thanks again. I'll add this check as soos as i can

**Comment by Sav22999** [comment]
I've just release the [0.2.10b](https://github.com/Sav22999/common-voice-android/releases/tag/0.2.10b) that should solve this bug

**Comment by Booteille** [comment]
> @Booteille I've just seen that now, on F-droid, there is a newer version. Please, tell me if the bug is fixed

I still didn't receive the update on F-Droid. I'll keep you in touch once I got it.

**Comment by Sav22999** [comment]
@Booteille yes, f-droid need some days to receive the update

**Comment by Booteille** [comment]
Okay, I just installed the last update via f-droid and everything is working fine. Thanks!
