### ISSUE TITLE
[BUG] Crash after signing in with GitHub

### ISSUE THREAD

**Issue by Moini** [Sav22999/common-voice-android#40]
_Android (OS) version:_ LineageOS 16.0
_Android (OS) language (in English):_ German
_App release:_ 0.2.9B
_App language (in English):_ German
_Device RAM:_ 2GB
_Display size (in Inches):_ ?
(Optional, but recommanded) _Device model (and brand):_ Moto X4
_From what store have you installed the app?:_   F-Droid
_Are there installed Google Services on your device?_ No (Nothing)

**Description bug**

**How to reproduce the bug**
1. Open App
2. Tap on Login/Register
3. Tap on Login with GitHub
4. Enter username and password for GitHub
5. Tap on 'Sign in'
6. Give permission
7. Get to see a form where one can fill in user data (Email address, language,...)
8. Form vanishes after about 0.5 seconds, because the app crashed

**Screenshots**
-

**Additional context**

I had tried the email option before this, but it didn't work, either. First it took a long time for the email to arrive, and then, after clicking the link, I only get a JSON document at voice.mozilla.org that looks like this:
`{"message" : ""}`

Login on my desktop browser fails, too, I only ever get redirected to the login page. I have an account, and it had worked previously. It's as if they don't want my contributions ... (probably, it would work with Chromium - things always work there when they don't work in FF) :woman_shrugging:

**Comment by Sav22999** [comment]
@Moini you said that the login doens't work in the Desktop browser, right?

**Comment by Sav22999** [comment]
Maybe it's an issue related to Common Voice (this is not an official app, so I cannot talk directly to Common Voice developers team).
I advice to try again, maybe there's some problems. If it doesn't work yet (on desktop), please open an issue on their repo. Instead, if on website desktop it will work correctly, but in the app the login won't work, please, come back here. I'll reopen this issue in that case 😄

**Comment by Moini** [comment]
You are saying that a crash in your app is not a bug, even if it is related to an issue with an external website? That's ... an unusual notion. 

Crashes should *never* happen.

**Comment by Sav22999** [comment]
@Moini Yes, it's absolutely true! 😄 
The crash in the app is probably the same of #36 and also #29 .

I say that, if the issue is present also on https://voice.mozilla.org, so it's better to contact directly Mozilla Support, because I don't have any directly contact with them 😄

**Comment by Moini** [comment]
Yeah, I know. I thought it would be worth mentioning it, in case it plays a role. Hence I've put it under 'context'. 

It also explains why I had to use the GitHub option at all, even if I wouldn't normally use it when there's a non-third-party option available. But both failed... 

Do any of them work for you?

**Comment by Sav22999** [comment]
I use Firefox account and it works correctly. In the 0.2.9b I've fixed a bug with Google login, so also it should works. And Github login, until your report, didn't have issue.

You can contact me also on Telegram (if you go to "Settings" you can find the option "Contact the developer to Telegram" 😄 

I'm investigating about this bug, because in 0.2.2b I implemented a bug-fix of this. But, clearly, it didn't worked 😄 

Thanks fot the report.

**Comment by Sav22999** [comment]
@Moini unfortunately also me get that empty message:
![immagine](https://user-images.githubusercontent.com/32335378/78308259-54431900-7548-11ea-9955-c7956f2e6853.png)

This happens when I copy the verification link from email. Instead, if I click on the button (in the verification email) it works correctly. I don't know why. This i an issue of the main server, not of my app.
![immagine](https://user-images.githubusercontent.com/32335378/78308497-ec410280-7548-11ea-909f-e3c70dffa409.png)

**Comment by Sav22999** [comment]
@Moini I've got that error in same situation, but "random". I don't know why.
In addiction, I've fixed a bug in the code of the app, so it shouldn't crash anymore for this error (basically, there was a bug while it shown the message dialog error).

Anyway, the "empty json" `{"message":""}` is not the same bug.
I noticed that if you ask the verification code on a web browser and you open it in another web browser, it returns always that json. Of course, it's a voice.mozilla.org issue, but I would like, at least, show a message for users.

I need more information. Have you tried to ask the verification code in the app and have you opened it always in the app? (tap on verification link > Open with > Common Voice). Please, update me. Thanks

**Comment by Moini** [comment]
Thanks for the crash fix.

There is no 'Open with' in my K9mail... I can only 'Open' or 'Share'. 

I guess there's no way to copy-paste the link into the app?

**Comment by Sav22999** [comment]
Ok, so it is the problem. I advice you to "copy" the link in your notepad (google keep? onenote? ect.) and then click there. It should show "Open with" and select "Common Voice" 😄 

Update me.

A solution could be to add a textbox where you can "paste" your verification link. I will think how to implement that 😄

**Comment by Sav22999** [comment]
I've just release 0.2.10b -> it should "solve" the issue (at least, it shouldn't see anymore `{"message":""}`)

**Comment by Sav22999** [comment]
@Moini any news? You can find the latest update on F-droid too. Please, update me, otherwise I'll consider this issue as "Fixed"

**Comment by Moini** [comment]
I've updated yesterday, no time to try it out yet.

**Comment by Moini** [comment]
It worked! I was able to login with Github today. Thank you!

**Comment by Sav22999** [comment]
Perfect 😄  thanks for the report 😄

**Comment by Moini** [comment]
Btw. - a usability observation: It's not obvious how to get back from the uneditable form view to the actual app. A button here would help. Or maybe the form view doesn't need to be shown at all. 
At first I thought it would be for adding info, but it's not editable. So I'm not really sure what it's for. 

If it's about showing which account is active, then a short message à la 'you are now logged in as user xyz with email address abc' would seem more useful to me.

Additionally, I found an auto-play option, at least it sounds like that in the German translation ('Clip beim Laden automatisch abspielen' - 'Play clip automatically while loading' (while???)). It doesn't lead to clips playing automatically, at least after I have up- or downvoted a clip, I still need to tap on the play icon in order for the next one to be played.

Would you like bug reports for these two things?

**Comment by Sav22999** [comment]
@Moini I'm so sorry, unluckly I'm not German. You can fix translation on crowdin 😄 it should be "after" and not "while" loading.

I'll add a button "Back" in the "LoginActivity"

**Comment by Sav22999** [comment]
@Moini If you want to open a new issue for each bugs, it would be good.
But, you can translate yourself the app on [crowdin](https://crowdin.com/project/common-voice-android)

**Comment by Moini** [comment]
Thanks! I've opened an issue for the one where you haven't already decided upon a solution.

**Comment by Moini** [comment]
Updated translations. Switched to informal 'Du', as it was inconsistent, and mobile apps often use it.

**Comment by Sav22999** [comment]
@Moini I've just approved your suggestions. Thanks 😄  in the next update, i'll update also german translation 😄

**Comment by Sav22999** [comment]
@Moini [here](https://crowdin.com/translate/common-voice-android/1/en-de#59) you suggested more strings ... what is the right one?

**Comment by Moini** [comment]
Sorry, always the one that was done last. I guess I should have removed the other suggestions, thought they'd overwrite...

**Comment by Moini** [comment]
Removed those that I've meant to be overwritten. Thank you!

**Comment by Sav22999** [comment]
Really thanks 😄

**Comment by Sav22999** [comment]
@Moini `Jemals` means `Ever`, but `ever` in that contest is the synonim of `of all time`. Is the translation correct?

**Comment by Moini** [comment]
Yep, jemals is fine, I was aware of where the string occurs in the interface. 'Immer' is definitely wrong, it means 'always'. 

Other options starting with 'Seit' (since) would need to include a date or start point, like 'Seit Registrierung' (starting from date of registration). A simple 'Alle' would work, too, but it's less close to the original, because it has nothing to do with time (just means 'all').
 
In English, one would commonly say 'All time'.

**Comment by Sav22999** [comment]
@Moini yes, okok. In English I've used "Ever" that means also "Never". So, I asked to you for this reason 😄 
I've implemented the "Back" button in the ActionBar in "Login" (in 0.2.11b it'll be!) as you asked 😄

**Comment by Moini** [comment]
Molte Grazie! :D
