### ISSUE TITLE
[SUGGESTION] Create an option to log app activity for debugging purposes.

### ISSUE THREAD

**Issue by mrwesleycrusher** [Sav22999/common-voice-android#41]
**Description feedback/suggestion**
When the "Maintain logfile of activity" radio button is active in settings, the app saves a logfile to the device and the actions performed by the user during the session. Whenever an error occurs, the logfile holds the stack trace. This logfile can then be attached to github issues regarding bugs in the app.

**Additional context**
Since this app doesn't have a large development team, in order to help troubleshoot errors on various devices, it might be beneficial for users to be able to attach a session log to issues posted on GitHub. Although I don't think logging activity in an application should be mandatory, for those who want to contribute to development it would be helpful to have the option

**Comment by Sav22999** [comment]
Good idea. Now, if there is and exception, it should show a message dialog and there is the button "Details" where it prints the exception.

**Comment by bentleypark** [comment]
@Sav22999 Do you know the library called [Sentry](https://github.com/getsentry/sentry-java)? Using this library, the crash log and device details will be reported automatically when the app is crashed.

**Comment by Sav22999** [comment]
@bentleypark Nope, I don't know it. Is it open source and compatible with F-Droid?

**Comment by bentleypark** [comment]
@Sav22999 I am not familiar with F-droid. Senty is opensource. Once you join [sentry.io](sentry.io) and use the library, you can get crash log throuh the site.

**Comment by Sav22999** [comment]
I understand. I don't really like the idea, also because data are sent to an external website, and I don't really know what theyvdo with those data.

It will be better find a solution to save on file, and then you should be able to send the log here, as file

**Comment by bentleypark** [comment]
I get it. Let me get this straight, first log needs to be saved as file and user can access the file to be able to upload on here. And we shoud give the option to user if they can save a logfile or not.

**Comment by bentleypark** [comment]
Using [RxLogs library](https://github.com/umair13adil/RxLogs/), log can be captured as file on device. Please see the picture below.   
![Uploading Screenshot_20200928-111239_My Files.jpg…]()

**Comment by Sav22999** [comment]
I've seen. Could you rename the file name? (just "log.txt" and if exists already a log.txt it should be renamed as "log_old.txt")

In addition, as usual, is it compatible with F-Droid policy?

**Comment by MrIndeciso** [comment]
I was thinking of using the good old Timber instead, saving the logs in a SharedPreferences file.
RxLogs seems a little bit too advanced and bloated for what our usage would be.

**Comment by bentleypark** [comment]
@MrIndeciso I think Timber is a good option for debugging. @Sav22999 This feature is only for developer who wants to contribue and report a bug?

**Comment by Sav22999** [comment]
@bentleypark Have you tried the app?
The "log feature" is available for everyone who wants to report a bug, not just for developer :smiley:

**Comment by bentleypark** [comment]
@Sav22999 I have used app 😁
Is it ok use RxLogs to deveop this feature? Or Timber? How can I find put if the library is compatable with F-Droid policy?

**Comment by Sav22999** [comment]
> @Sav22999 I have used app 😁
> Is it ok use RxLogs to deveop this feature? Or Timber? How can I find put if the library is compatable with F-Droid policy?

It should be open source, and Google Service free.
You could try, at least, ask to the F-Droid forum

**Comment by bentleypark** [comment]
I can work on this with Timber which is compatable with F-Droid.

**Comment by Sav22999** [comment]
@bentleypark perfect

**Comment by bentleypark** [comment]
Is there any use case which accesses external storage except for saving log file?

**Comment by Sav22999** [comment]
@bentleypark In future i would like implementing also the "Export settings"/"Import settings" and also saving of recordings (see #107)

**Comment by bentleypark** [comment]
@Sav22999 On pulic area or private area(eg. /Android/data/org.commonvoice.saverio/foldername)?

**Comment by Sav22999** [comment]
What do you mean with "Public area"?

**Comment by bentleypark** [comment]
Like Download Directory.  Are you considering applying Scoped storage when implemeting #107 feature?

**Comment by Sav22999** [comment]
Just the user should be able to change it, but the default is "private storage"

**Comment by bentleypark** [comment]
Ok. if "private storage" will be choosen, the permission of External Storage should be removed.

**Comment by Sav22999** [comment]
But you should be able to change, si it's easier it remains

**Comment by bentleypark** [comment]
I know. But I don't undetstand why the user should be able change where to save.

**Comment by Sav22999** [comment]
Because the user should be able to change always everything, this is my opinion :smile:
