### ISSUE TITLE
[BUG] Auto-play option does not seem to work

### ISSUE THREAD

**Issue by Moini** [Sav22999/common-voice-android#43]
Android (OS) version: LineageOS 16.0
Android (OS) language (in English): German
App release: 0.2.10B
App language (in English): German
Device RAM: 2GB
Display size (in Inches): ?
(Optional, but recommanded) Device model (and brand): Moto X4
From what store have you installed the app?: F-Droid
Are there installed Google Services on your device? No (Nothing)

**Description bug**

**How to reproduce the bug**
1. Go to  Settings
2. Activate the first option (play clip automatically after loading)
3. Expect it to play the next clip after the previous one has been either confirmed to be correct or incorrect.
4. The clip is loaded, but not played automatically. I still need to press the play button.

**Comment by Sav22999** [comment]
@Moini are you sure the option is "on" ?

**Comment by Moini** [comment]
Oops. :flushed: 
Somehow, I associated it having color at all with it being active.
Very sorry!

**Comment by Sav22999** [comment]
@Moini so, does it work correctly? 😄

**Comment by Moini** [comment]
Yes! :heart:

**Comment by Sav22999** [comment]
Perfect. No problem 😄 
If you need other support or if you want suggest/report something else, I'm here! 😃

**Comment by Moini** [comment]
Not today anymore - maybe later :) Thanks and Buona notte!

**Comment by Moini** [comment]
Btw.... Where is that auto-play option in the xml file? Now that I come to think of it... I didn't improve it, because it wasn't there... :confused:

**Comment by Moini** [comment]
Found it.

**Comment by Sav22999** [comment]
Yes, it is there. This is the relative German string: https://crowdin.com/translate/common-voice-android/1/en-de#493

**Comment by Moini** [comment]
Yeah. That site is strange - why does it have pagination in a scroll-down list...?

**Comment by Sav22999** [comment]
I don't know. Anyway, you can find at the bottom-left two arrows to navigate in the pages (there are 3 pages of strings).
![immagine](https://user-images.githubusercontent.com/32335378/78848387-e9935100-7a11-11ea-8d8d-16a4f939b29e.png)

**Comment by Sav22999** [comment]
@Moini  In addition, if you like this project, leave a star, so you'll receive news on github dashboard 😄 
![immagine](https://user-images.githubusercontent.com/32335378/78848474-2eb78300-7a12-11ea-8e80-a449603f3eee.png)

**Comment by Moini** [comment]
Yeah, I hadn't expected the pagination, so didn't find the other strings at first. I'm good at finding usability traps, lol ... (or falling into them, that is).
