### ISSUE TITLE
[TRANSLATION] French

### ISSUE THREAD

**Issue by exilexi** [Sav22999/common-voice-android#46]
_Language name in English:_ French
_Language name (long, in native language):_ Français
_Language code in Common Voice:_ fr_FR
_Language code in [Android Studio](https://android.googlesource.com/platform/frameworks/base/+/android-9.0.0_r1/core/res/res/values/locale_config.xml):_ fr

In profile > gender
Female is translated with "femelle". Femelle is strictly for animals and biology - we’d use **Féminin**. I assume that Male is translated "Mâle" - it should be **Masculin**.

Thanks for your great work!

**Comment by Sav22999** [comment]
@exilexi please, if you have sime minutes, check every strings. You can do that (and change too) directly on Crowdin 😁 thanks for support

**Comment by exilexi** [comment]
Thank you @Sav22999! Still a beginner with Github etc. I’ve signed up to Crowdin and will be making edits there :)

**Comment by Sav22999** [comment]
@exilexi If you're new on Crowdin, probably you don't know that you can navigate in pages 
![immagine](https://user-images.githubusercontent.com/32335378/79329908-e3710900-7f18-11ea-91cd-21ed484e57ef.png) using those buttons (bottom-left).
I think you checked just the first page 😄  thanks for feedbacks, I've approved those!

**Comment by exilexi** [comment]
@Sav22999 I think we're good now :) There a couple that I changed but didn't notify you on, sorry about that

**Comment by Sav22999** [comment]
@exilexi No worry, I can see the "Activity" in a specific section. So, I can find easily strings modified 😄

**Comment by Sav22999** [comment]
@exilexi I've just updated English translations, so please could you translate the app again. I've added screenshots too on crowdin, so it's simpler the translation
