### ISSUE TITLE
[SUGGESTION] Add "Report" button in Listen (and Speak) section

### ISSUE THREAD

**Issue by Sav22999** [Sav22999/common-voice-android#47]
**Description feedback/suggestion**
Add "Report" button to report a wrong sentence/clip.
When you press on the button, it should show to you some "default" sentence, such as on the website.

Speak:
- Offensive language
- Grammatical / spelling error
- Different language
- Difficult to pronunce
- Other > Textbox to specify it

Listen:
- Offensive speech
- Grammatical / spelling error
- Different language
- Other > Textbox to specify it

**Comment by PanderMusubi** [comment]
Yes, for Dutch language, often Frysian text is shown accompanying audio is played.

**Comment by Sav22999** [comment]
@PanderMusubi I've just released 1.2 which have many new features, included "Report" feature!
