### ISSUE TITLE
[BUG] Device Rotation Handling

### ISSUE THREAD

**Issue by totoroot** [Sav22999/common-voice-android#48]
### Description feedback/suggestion

Handle device rotation properly

When you rotate the device in voice clip verifcation the webpage reloads which brings up a new voice clip every time. With the autoplay feature turned on this leads to overshadowing of voice clips. The expected behaviour would be that a voice clip persists when the device is rotated.

I would like to take a look at it myself on the weekend and will create a pull request if I manage to fix the issue. Thank you for your efforts into making participating in the Common Voice Project much more convenient. Already looking forward to the ability to record clips!

Cheers :v:

**Comment by Sav22999** [comment]
@totoroot I think this is a feature/bug of Android, actually. It looks like it reload the activity... but, I'll try to fix it 😄  thanks.

If you want to contribute, I advice you to help me to add Speak section #42 -> that's the priority now 😄  (but, of course, if you want to work on this it's ok for me 👍 )

Have a nice day!

**Comment by totoroot** [comment]
Ok perfect, I'll take a look at that too :ok_hand:

**Comment by Sav22999** [comment]
@totoroot bug fixed in 1.0b
