### ISSUE TITLE
[TRANSLATION] Swedish

### ISSUE THREAD

**Issue by klasrocket** [Sav22999/common-voice-android#5]
Just started translation to swedish
https://github.com/klasrocket/common-voice-android/tree/new-language-swedish

**Comment by Sav22999** [comment]
@klasrocket Thank you very much! In these days I will update the app and so there will be other strings. I hope you will update these with the new 😃

**Comment by Sav22999** [comment]
It is now supported officially (0.0.14a). Thank you very much!
