### ISSUE TITLE
[SUGGESTION] Explain what Common Voice is.

### ISSUE THREAD

**Issue by uniqx** [Sav22999/common-voice-android#50]
**Description feedback/suggestion**

The F-Droid store listing does not explain what common voice is. I don't know what common voice is for example and it's rather confusing to read your app description for me. It would be great if you could add sentence or two about that somewhere at the beginning of your app description.

**Comment by Sav22999** [comment]
Sure! I'll add the description in the "First-run tutorial" 😄 
Anyway, Common Voice is a project of Mozilla https://voice.mozilla.org.
He's goal is to collect voices (recordings) in every language available (also minor language which big companies don't invest to) and create an open dataset of voice, which everyone can use for every scope 😄  in the official website you can find the official description.
Thanks for the feedback

**Comment by uniqx** [comment]
Thank you. In the first-run tutorial is a good place to explain things. :smile: But would be great to learn about common voice even before installing. I was refering to the F-Droid store listing:

https://github.com/Sav22999/common-voice-android/blob/master/fastlane/metadata/android/en-US/full_description.txt

**Comment by Sav22999** [comment]
@uniqx In the 0.2.12a branch you can find a new description. I've added a short description of the project, and then I've inserted a link to CV 😄

**Comment by uniqx** [comment]
Thank you. :slightly_smiling_face:
