### ISSUE TITLE
[SUGGESTION] Add statistics (anonymous and deactivable)

### ISSUE THREAD

**Issue by dag7dev** [Sav22999/common-voice-android#51]
It would be nicer, for your convenient, (and our curiosity, of course) to understand how many users are currently using the application.
Maybe you should try to find a way to know how many users are currently using the application, since F-Droid lacks of this functionality.

**Comment by Sav22999** [comment]
Yes, sure! I can add a "switch on-off" in the Settings. Thanks for the feedback

**Comment by Sav22999** [comment]
I've just created also the API: https://saveriomorelli.com/api/common-voice-android/

**Comment by Sav22999** [comment]
I will arrive with 1.0b 👍
