### ISSUE TITLE
[BUG] Cannot log in using Mozilla account

### ISSUE THREAD

**Issue by cloudrac3r** [Sav22999/common-voice-android#55]
_Android (OS) version:_ 9, LineageOS 16)
_Android (OS) language (in English):_ English
_App release:_ 0.2.11b
_App language (in English):_ English
_Device RAM:_ 6 GB
_Display size (in Inches):_ don't know
(Optional, but recommanded) _Device model (and brand):_ OnePlus 5T
_From what store have you installed the app?:_  F-Droid
_Are there installed Google Services on your device?_ microG only

**Description bug**

I cannot log in to my account in the app using my Firefox account. I enter my username, password, and 2FA code, and then the app blinks to a screen that asks for my age and gender, but then immediately changes to a screen with a notice saying the log in failed, and also shows a toast saying the log in was successful.

A message says that I must log in on the common voice website and accept the privacy policy, but logging in on the website does not affect the app, and I cannot find a privacy policy to accept.

Trying to log in again skips the email, password, and 2FA entry, but otherwise keeps doing the same thing.

**How to reproduce the bug**

Try to log in to the app with a Firefox account. My account had 2FA enabled, if that matters.

**Screenshots**

![](https://i.imgur.com/sdh7j9V.png)

**Comment by Sav22999** [comment]
@cloudrac3r You need to go to the website "voice.mozilla.org", do the login and you have to accept "Privacy Policy". Then, you can back to the app and do the login 😄 

Please, tell me if there are other issues

**Comment by Sav22999** [comment]
@cloudrac3r follow these steps:

- Go to https://voice.mozilla.org/en
- Do the login and you should get a screen similar to this one:
![immagine](https://user-images.githubusercontent.com/32335378/79692050-3de4cf00-8263-11ea-91de-5bbb0983b4d4.png)



You have to "tick" (check-on) the "Privacy policy" and the click on "Save".

**Comment by cloudrac3r** [comment]
Thank you for reading. I have already signed in on the website voice.mozilla.org with the same Firefox account. I can record and listen to clips on the website just fine. I do not know where to find the privacy policy so I can accept it.

I have used this account on Common Voice before, so maybe I already accepted the privacy policy then?

I'm sorry, I don't know what to do.

**Comment by Sav22999** [comment]
@cloudrac3r Oh, yes... if you used CV before, it should works 🤔 
I'm so sorry about this bug, I'll investigate.
Please, don't uninstall the app 😄 in the 1.0b will arrive also "Speak" section, finally! 😄

**Comment by cloudrac3r** [comment]
Let me know if there is anything I can do to help with this issue in the future.

**Comment by Sav22999** [comment]
So, I've just got the same problem with an emulator, but it's API 29 (Android 10).
Basically it get a Json as "null"... instead it contains data (if it's null, it means you didn't read Privacy Policy).
I've unsterstood the issue, so I hope I can fix it 😄

**Comment by Sav22999** [comment]
@cloudrac3r I've found the bug. Basically it stored a "old" cookie. I'll implement a fix in 1.0b, but you can Clear data and restart the app. Then it should work. Please, update me if this solution worked 😄

**Comment by cloudrac3r** [comment]
Clearing app data does seem to have let me log in now. Thanks!
