### ISSUE TITLE
[SUGGESTION] Listen: download the next clip while listening to the current one

### ISSUE THREAD

**Issue by tuxayo** [Sav22999/common-voice-android#60]
**Description feedback/suggestion**
Between two recordings, there is a break that heavily depend on the current internet connection.

Similar to #61 as the idea is to do stuff in the background to ideally never have to wait.

**Comment by Sav22999** [comment]
@tuxayo yes, now it does this thing. The first time you open Listen it downloads 2 clips, after you validate the first one it shows to you the second clip, and download and other in background

**Comment by tuxayo** [comment]
Great!
