### ISSUE TITLE
[SUGGESTION] Listen: send the result of validation while listening to the next clip

### ISSUE THREAD

**Issue by tuxayo** [Sav22999/common-voice-android#61]
**Description feedback/suggestion**
Between two recordings, there is a break that heavily depend on the current internet connection.

Similar to #60 as the idea is to do stuff in the background to ideally never have to wait.

**Comment by Sav22999** [comment]
@tuxayo I've answered in #60.
Anyway, thanks for the feedback. If you have other ideas, please open a new issue. 😃

**Comment by tuxayo** [comment]
> now it does this thing

In which version? On 1.1b there is still a network way between listening to two recordings.

**Comment by Sav22999** [comment]
I think from 0.2b.

Open Listen (and wait). Then, you shouldn't have problems.
If you get issues, please could you contact me to Telegram?

**Comment by Sav22999** [comment]
Added in #89
