### ISSUE TITLE
[Feedback] The idea of not doing batches is really great

### ISSUE THREAD

**Issue by tuxayo** [Sav22999/common-voice-android#62]
**Description feedback/suggestion**
Thank you 💚

It's a big reason I use the app. Maybe it's better for some people to have batches[1] but in my case, an endless stream of tasks feels much more efficient.

[1] Like in https://voice.mozilla.org/

**Comment by Sav22999** [comment]
@tuxayo thank you very much to you, because you use the app and you opened some issues to improve it.

If downloaded the app from Google Play Store I would really like a review there. Otherwise, it's not a problem.

If you need something else, remember you can also contact me on Telegram

**Comment by tuxayo** [comment]
> If downloaded the app from Google Play Store I would really like a review there.

> If you need something else, remember you can also contact me on Telegram

Sorry, I'm trying to avoid these non-libre tools ^^"

**Comment by tuxayo** [comment]
Also, thanks to the app, I'm using more Common Voice :D
Because I had audio[1] and UI issues[2] with the website with Firefox Android which I didn't found yet the motivation to troubleshot.

[1] corrupted my recordings often. From time to time, website&Firefox still "holding" the audio channel and blocking the other apps until I killed the browser.

[2] after 5 recordings, on the review screen before upload, the small popups with the written text would overlap the buttons. Requiring to "guessclick" to play or rerecord
