### ISSUE TITLE
[SUGGESTION] Record: send the recoding while doing the next one

### ISSUE THREAD

**Issue by tuxayo** [Sav22999/common-voice-android#63]
**Description feedback/suggestion**
To avoid an upload break that heavily depends on the current internet connection.

**Additional context**
https://voice.mozilla.org actually does that. The batch of 5 is send when the next batch is being done.

**Comment by Sav22999** [comment]
@tuxayo This could be a good idea, but I think very difficult. If there is an error in the sending phase it would be very difficult to manage. But, I'll try to do it 😁

**Comment by tuxayo** [comment]
> If there is an error in the sending phase it would be very difficult to manage.

Retry one or two times (for networks issues) and then drop and tell the user? Even now, if there is an error in the sending phase the recording will be lost if it doesn't work after manual retry.

**Comment by tuxayo** [comment]
> But, I'll try to do it 

Thanks a lot :D

**Comment by Sav22999** [comment]
Added in #89
