### ISSUE TITLE
[TRANSLATION] Slovak

### ISSUE THREAD

**Issue by tadeasbucha** [Sav22999/common-voice-android#67]
_Language name in English:_ Slovak
_Language name (long, in native language):_ slovenčina
_Language code in Common Voice:_ sk-SK
_Language code in [Android Studio]:_ sk-SK

**Comment by Sav22999** [comment]
@tadeasbucha I've added Slovak on Crowdin.
Thank you very much for contributing to my project!

**Comment by Sav22999** [comment]
@tadeasbucha you can translate the app in Slovak, but Common Voice doesn't support, now, your language yet https://voice.mozilla.org/sk. I'm so sorry.
(But you can translate anyway the app, so as soon as Common Voice will support the language, the app will be already ready 😄 )

Please update me if you want to translate or not the app

**Comment by tadeasbucha** [comment]
> 
> 
> @tadeasbucha you can translate the app in Slovak, but Common Voice doesn't support, now, your language yet https://voice.mozilla.org/sk. I'm so sorry.
> (But you can translate anyway the app, so as soon as Common Voice will support the language, the app will be already ready 😄 )
> 
> Please update me if you want to translate or not the app

I'd be happy to help you with the translation of the app, just let me know what to do :)

**Comment by Sav22999** [comment]
I've added Slovak on Crowdin. So, you can translate directly there and then I'll approve 😁 thanks
(If you can speak other languages you can translate the app also in those languages)

**Comment by Sav22999** [comment]
@tadeasbucha if you don't translate in this language anymore I'll close this issue

**Comment by tadeasbucha** [comment]
@Sav22999 I am working on the translation continuously, though I don't have time for it every day. Please bear with me.

**Comment by Sav22999** [comment]
@tadeasbucha ok, no problem. I just wanted to know 😄 take all the time you need

**Comment by Sav22999** [comment]
@tadeasbucha I saw you translated all 😄  thanks you. I've added 3 strings yesterday, when you have some minutes translate them too, if you want
