### ISSUE TITLE
[SUGGESTION] Swipe left/right instead of button pressing

### ISSUE THREAD

**Issue by Diddian** [Sav22999/common-voice-android#74]
Would be love if instead of clicking thumbs up and down a Tinder-like gesture based rating along with the existing autoplay would make approving voice messages much faster!

**Comment by Sav22999** [comment]
@Diddian thank you for your suggestion. It's a good idea (I've never used Tinder, so I don't know how it works), but I'll try to implement this feature 😄  thanks

**Comment by Diddian** [comment]
@Sav22999 basically Swipe right to approve and Swipe left to disapprove [Gif for animated reference](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fyourbusinessmyopinion.files.wordpress.com%2F2015%2F11%2Fgiphy-2.gif&f=1&nofb=1)

**Comment by Sav22999** [comment]
@Diddian Ok, so probabily that animation (the "card" which goes to right/left) is very very heavy... and the goal of the app is to be "light" and to contribute to Common Voice everywhere easily ... if you want to animation, you can use website... but, anyway, I can add "swipe-left" and "swipe-right" to appreove/reject, maybe "swipe-up" so report the sentence (but you will be able to turn on or turn off in Settings, for "Gestures")

**Comment by Sav22999** [comment]
@Diddian I've added some gestures (now they are in Beta version).
![image](https://user-images.githubusercontent.com/32335378/81388504-aa434780-9118-11ea-8568-00e388ae7352.png)

I've tried to add "swipe-left" and "swipe-right" to validate/reject but I think it's less intuitive and not so many comfortable... but, how you can see, I've added other gestures.

Please, tell me a feedback about them 😄
