### ISSUE TITLE
[SUGGESTION] Send recordings without having to listen to each one of them

### ISSUE THREAD

**Issue by a3nm** [Sav22999/common-voice-android#75]
Currently, the app forces you to listen to every clip that you record before you send it (unlike what the Mozilla website is doing). I understand this can make sense, at least initially, to avoid sending garbage, but after a while it's really a waste of time.

Could there be an option in settings to disable this and give you the option to send the recorded clip without having to listen to it?

Thanks for developing this app!

**Comment by Sav22999** [comment]
Yes, that option will arrive in future 😄 it's in my "to-do" list.
My idea was force user to listen to his audio to avoid rubbish... many users wrong just a letter, for example, and that recording is not anymore valid... but of course it should be a choose of user 😄 
thanks for the suggestion 😄

**Comment by Sav22999** [comment]
@a3nm I've added this feature in 1.4

**Comment by a3nm** [comment]
Wow, that's really impressive, many thanks! I'll see it when it lands in F-droid.


On May 9, 2020 1:36:40 AM GMT+02:00, Saverio Morelli <notifications@github.com> wrote:
>@a3nm I've added this feature in 1.4
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Sav22999/common-voice-android/issues/75#issuecomment-626063932

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by a3nm** [comment]
Sorry, I have just installed 1.3.1 from F-droid, which talks about "Skip recording confirmation" in "NEW IN VERSION 1.3.1". But I don't see the option in the settings. Would you have any idea about what may be going on? Thanks!

**Comment by Sav22999** [comment]
@a3nm  It's very weird. The feature is implemented in 1.4 ... 🤔 
Please, verify the version installed is the 1.4.1 (from app Settings, in the top-right) 😄

**Comment by Sav22999** [comment]
@a3nm The option should be in `Settings | Speak | Skip recording confirmation` 😄

**Comment by a3nm** [comment]
Sorry, as it turns out after updating the repos, version 1.4.1 is
available on F-droid and it has the setting, which works fine. Again,
thanks a lot for this!

Best,

-- 
Antoine Amarilli
