### ISSUE TITLE
[SUGGESTION] Publish the app on F-Droid, Google Play Store and Aptoide

### ISSUE THREAD

**Issue by Sav22999** [Sav22999/common-voice-android#8]
**Description feedback/suggestion**
Publish app also on F-droid, Aptoide, Amazon App-Store and Huawei Store (in addition to Google Play Store).

**Comment by PoorPocketsMcNewHold** [comment]
https://apt.izzysoft.de/fdroid/index/apk/org.commonvoice.saverio While waiting to suggest the application to be added to the main F-Droid repo, It has already been added to the izzysoft F-Droid repo.

**Comment by Sav22999** [comment]
Oh, great! I've already suggested the app in gitlab repo of fdroid. I'm waiting a their answer

**Comment by Sav22999** [comment]
App available now (in Beta version) on Google Play Store. You need to activate the Beta on your account [here](https://play.google.com/apps/testing/org.commonvoice.saverio) and then download from the apps store https://play.google.com/store/apps/details?id=org.commonvoice.saverio&hl=it

**Comment by Sav22999** [comment]
Available on Aptoide https://common-voice-android.en.aptoide.com/?store_name=sav22999&app_id=49778274

**Comment by Sav22999** [comment]
Available on F-Droid https://f-droid.org/it/packages/org.commonvoice.saverio
