### ISSUE TITLE
[SUGGESTION] New themes

### ISSUE THREAD

**Issue by Sav22999** [Sav22999/common-voice-android#83]
**Description feedback/suggestion**
Now there are "light" and "dark" theme.
There should be more themes; at least: "Auto" (based on the time it changes from Light to Dark and vic.)

**Comment by dag7dev** [comment]
Auto would be great! You could base this option by using device settings (newest Android could request to applications to change the theme automatically) or you could open a popup which let the user decide between light and dark

**Comment by Sav22999** [comment]
@dag7dev Yes, I should work on it as soon as I have some spore time.
