### ISSUE TITLE
[SUGGESTION] Create "wiki" or documentation

### ISSUE THREAD

**Issue by Sav22999** [Sav22999/common-voice-android#85]
**Description feedback/suggestion**
Document how this project works

**Comment by bentleypark** [comment]
@Sav22999 Is ther any document about commonvoice api usage and api response?

**Comment by Sav22999** [comment]
No

**Comment by bentleypark** [comment]
How could you connect the app with commonvoice api without reference?

**Comment by Sav22999** [comment]
Common Voice APIs exist, but they aren't documented. I've analysed the website (reverse engineering)

**Comment by MrIndeciso** [comment]
Yeah you can do stuff on the website and look at the requests it makes through Developer Tools.
Or you can look at their code https://github.com/mozilla/common-voice/tree/main/server/src and try to work out what it does.

**Comment by bentleypark** [comment]
Thanks @MrIndeciso

**Comment by Sav22999** [comment]
In the new release will be also the CV Android documentation ("API.md" file)
