### ISSUE TITLE
[BUG] Recording playback randomly doesn't work

### ISSUE THREAD

**Issue by Sobsz** [Sav22999/common-voice-android#86]
_Android (OS) version:_ 6.0.1
_Android (OS) language (in English):_ English
_App release:_ 1.4.4 (106)
_App language (in English):_ Polish
_Device RAM:_ 3GB
_Device display size (in Inches):_ 5in
(Optional, but recommended) _Device model (and brand):_ Xiaomi Redmi 3S Prime
_From what store have you installed the app?:_ Google Play Store
_Are there installed Google Services on your device?_ Yes

**Description bug**
When trying to listen to my recorded voiceline, sometimes the recording doesn't play and the icon stays in a "playing" state. It is possible to stop and restart playing, though the voice still isn't heard.
Trying to rerecord it causes the microphone icon to turn into a stop icon, but nothing else. Tapping the icon again does nothing. It is possible to send the recording, though I don't know if it actually sends any audio. Switching to another app and back seems to resolve the bug, as does leaving the Speak section and re-entering it.

**How to reproduce the bug**
1. Set all the on-off switches to the "on" position (that's how I have it).
2. In the Speak section, start and then quickly stop recording.
3. Play back the recorded sound.
4. If playback stops by itself, return to step 2. Otherwise, congrats; you got the bug!

**Screenshots**
https://files.catbox.moe/xulbud.mp4

**Comment by Sav22999** [comment]
@Sobsz this is very weird 🤔 maybe there are other app which use "mic" ... so "Common Voice App" can't catch the audio?

**Comment by Sav22999** [comment]
@Sobsz Ok, I've checked... so this bug is present just if you tap "Start record" and then (quickly) "Stop record" right? Doesn't the app return an error (like EX-S12)?

**Comment by Sobsz** [comment]
Nope, it happens regardless of the duration. I just wrote to do it quickly in order to save time (probably shouldn't have done that but oh well).
No error code is displayed either. I'd attach a log.txt, but that option doesn't seem to exist? (I saw it in Crowdin, so I assume it either existed at some point or is planned to be implemented.)

**Comment by Sav22999** [comment]
@Sobsz "Logs" feature isn't available now (I'm working on some other improvements now, but i'll implement as soon as). Anyway, thanks to report this bug. If you don't tap quickly "start" and then "stop" that bug is yet present or everything is ok?

**Comment by Sobsz** [comment]
It seems to happen randomly, regardless of how long or short the recording is. I'd say once every 8 tries?
________________________________

**Comment by Sav22999** [comment]
I really don't know... I've never got that error, and I've recorded over 100 sentences in a single time... but, anyway, I'll try to replicate that error and fix it. Thanks.
I add the "not-reproduced" label to this issue; it's just to categorise issues, but I try to fix all of them.

**Comment by Sobsz** [comment]
Just recorded a couple dozen sentences with the "Recording indicator sound" option off and the bug _didn't_ occur; turning it back on eventually resulted in the bug. Maybe this information could be somewhat helpful?

**Comment by Sav22999** [comment]
@Sobsz Ok, great! Thanks. I'll check 😄 
In the meanwhile please use the app without that option (so turn off "Recording indicator sound"). Sorry for the inconvenince

**Comment by Sobsz** [comment]
Ehh, I turned it off anyway because it actually seems to delay the recording until the sound finishes playing (not sure if that's intentional), so it's not a big deal. Thanks for being so vigilant though!
________________________________

**Comment by Sav22999** [comment]
@Sobsz Yes, you need to wait the end (some milliseconds) of that sound... otherwise that sound was recorded too, and that wasn't correct

**Comment by Sav22999** [comment]
Probably this bug is fixed in the (now beta) version #89
