### ISSUE TITLE
[SUGGESTION] Option to start (and stop?) recording automatically

### ISSUE THREAD

**Issue by Sobsz** [Sav22999/common-voice-android#87]
A small delay (1-2 seconds) should probably be added, to let the speaker to glance over the text (and to save a bit of time on the listeners' part). Not sure about auto-stopping, since you'd have tk send it manually anyway (unless?).

**Comment by Sav22999** [comment]
Ok, I've thought to this, but actually I think it's not properly useful.
I understand you need to press a button, but I think it's better... also because, when you add a feature, you need to add well... as the principle of IT "KISS" ... you should keep just useful features.
Sorry

**Comment by Sav22999** [comment]
@Sobsz I close this issue. Remeber you can open other issues when you want or you can contact me on Telegram always!
I'm thinking to create a Telegram group, what do you think?
