### ISSUE TITLE
[SUGGESTION] Preload sentences/clips in the background

### ISSUE THREAD

**Issue by Sobsz** [Sav22999/common-voice-android#88]
Probably too much effort for too little benefit, since it'd require something something asynchronous?, but I'm posting it just in case. All I know is the API probably supports it, as shown by the official website loading 5 things at a time and letting you go back to them (ooh that could be cool too- OK sorry, that's too much begging at once).

**Comment by Sav22999** [comment]
@Sobsz thanks, I think you mean the same thing of #63 and #61 , in that case I mark this as duplicate (and I inform you that I'm working to this thing too in these days)

**Comment by Sobsz** [comment]
Right, I should've probably looked first. Sorry! ._.

**Comment by Sav22999** [comment]
@Sobsz absolutely no problem! It's better open a duplicate than not open it 😄 thanks for suggestion anyway!
