### ISSUE TITLE
[BUG] Sending recording failed

### ISSUE THREAD

**Issue by tuxayo** [Sav22999/common-voice-android#91]
_Android (OS) version:_ 7.1.2 (LineageOS for microG 14.1)
_Android (OS) language (in English):_ French
_App release:_ 1.4.4 (106)
_App language (in English):_ Esperanto
_Device RAM:_ 2GB
_Device display size (in Inches):_ ?
_Device model (and brand):_ LG Nexus 5
_From what store have you installed the app?:_  F-Droid
_Are there installed Google Services on your device?_ Yes (microG)

**Description bug**
Error when sending a recording, it's not every time.

**Additional context**
In the website, I have errors when the recording is too long (it can happen easily with long phrases).
On the app, I also have error with short phrases but have to resent 3 times to success.

```
06-13 19:14:58.069   818   929 D AudioService: Stream muted, skip playback
06-13 19:14:58.120 25772 29030 I System.out:  >> text_sentence >> Li%20komencis%20prediki%20en%20la%20tirola%20regiono%2C%20formante%20plurajn%20malgrandajn%20komunumojn.
06-13 19:14:58.120 25772 29030 I System.out:  >> id_sentence >> 29ccbcec8b800bf4648de4183e9c2a24ea0e362521a4bfebfa51f6af58ba7363
06-13 19:15:01.613 25772 29030 I System.out:  >> text_sentence >> Li%20komencis%20prediki%20en%20la%20tirola%20regiono%2C%20formante%20plurajn%20malgrandajn%20komunumojn.
06-13 19:15:01.613 25772 29030 I System.out:  >> id_sentence >> 29ccbcec8b800bf4648de4183e9c2a24ea0e362521a4bfebfa51f6af58ba7363
06-13 19:15:07.104 25772 25772 I System.out:  -->> Something wrong: com.android.volley.TimeoutError <<-- 
06-13 19:15:07.112 25772 25772 I System.out: Sending recording failed!
06-13 19:15:09.185   818   818 W WindowManager: Attempted to remove non-existing token: android.os.Binder@ef03771
06-13 19:15:10.813   818   929 D AudioService: Stream muted, skip playback
```

```
06-13 19:14:33.155   818   929 D AudioService: Stream muted, skip playback
06-13 19:14:33.245 25772 28950 I System.out:  >> text_sentence >> Li%20komencis%20prediki%20en%20la%20tirola%20regiono%2C%20formante%20plurajn%20malgrandajn%20komunumojn.
06-13 19:14:33.245 25772 28950 I System.out:  >> id_sentence >> 29ccbcec8b800bf4648de4183e9c2a24ea0e362521a4bfebfa51f6af58ba7363
06-13 19:14:36.148 25772 28950 I System.out:  >> text_sentence >> Li%20komencis%20prediki%20en%20la%20tirola%20regiono%2C%20formante%20plurajn%20malgrandajn%20komunumojn.
06-13 19:14:36.148 25772 28950 I System.out:  >> id_sentence >> 29ccbcec8b800bf4648de4183e9c2a24ea0e362521a4bfebfa51f6af58ba7363
06-13 19:14:41.637 25772 25772 I System.out:  -->> Something wrong: com.android.volley.TimeoutError <<-- 
06-13 19:14:41.664 25772 25772 I System.out: Sending recording failed!
```

**Comment by Sav22999** [comment]
Yes, this is a known bug. Basically CV website is too slow in some hours, and Volley get a Timeout. I'm working to a new version (v2.0) that will have many new features and a new UI. The app is been developed from zero to improve everything. (There will be also "offline mode" and sending of recordings and clips in backgroud).
Please, be patient :)

**Comment by tuxayo** [comment]
No worries, it's just to report it as there didn't seem to be and existing ticket. Thanks a lot for your work :D

**Comment by Sav22999** [comment]
@tuxayo it's a pleasure. The "System.out" you see are useful just for me, when I develop the app, to see if everything work fine.
I've forgotten to delete them 😆 so sorry

**Comment by tuxayo** [comment]
> The "System.out" you see are useful just for me, when I develop the app

It turn out it was also useful for me to find out there was a timeout :P

I'm eager to try the new version! :D

**Comment by Sav22999** [comment]
@tuxayo Yeah, sure ;)
I've published the new release today, but bot Google Play and F-Droid needs time to publish apps, so... we need to be patient some other days 😂

**Comment by tuxayo** [comment]
>  but bot Google Play and F-Droid needs time to publish apps, so... we need to be patient some other days joy

I know that well, that's pretty scary in case of regressions (I've had that with my SMS app...) of external API change.
