### ISSUE TITLE
[BUG] Never ending "phrase loading" when server don't have new phrases to listen to

### ISSUE THREAD

**Issue by tuxayo** [Sav22999/common-voice-android#96]
_Android (OS) versio_Android (OS) version:_ 7.1.2 (LineageOS for microG 14.1)
_Android (OS) language (in English):_ French
_App release:_ 2.0 (113)
_App language (in English):_ Esperanto
_Device RAM:_ 2GB
_Device display size (in Inches):_ ?
_Device model (and brand):_ LG Nexus 5
_From what store have you installed the app?:_  F-Droid
_Are there installed Google Services on your device?_ Yes (microG)

**Comment by dag7dev** [comment]
Please explain more: what do you mean with "when server don't have new phrases to listen to", when this situation occurs?

**Comment by Sav22999** [comment]
@dag7dev This is a known bug. Basically when sentences you should record or clips you should validate finish, the app doesn't show to you a message like "There aren't any other clips to validate" but it remain to "loading..."

This happens, usually, when a language is not so common and so there aren't so many recordings/sentences

**Comment by dag7dev** [comment]
Ahh, I see, never happened to me. Thank you for the clarification!
