### ISSUE TITLE
[BUG] Report prompt cause the current recording to be dropped

### ISSUE THREAD

**Issue by tuxayo** [Sav22999/common-voice-android#98]
_Android (OS) version:_ 7.1.2 (LineageOS for microG 14.1)
_Android (OS) language (in English):_ French
_App release:_ 2.0 (113)
_App language (in English):_ Esperanto
_Device RAM:_ 2GB
_Device display size (in Inches):_ ?
_Device model (and brand):_ LG Nexus 5
_From what store have you installed the app?:_  F-Droid
_Are there installed Google Services on your device?_ Yes (microG)

**How to reproduce the bug**
1. Record a phrase that is a bit long (phone dependent, 5 lines I think in my case)
2. You need to scroll to make the "send recording" button visible (UI bug there maybe?)
3. This triggers the "swipe up"
4. Report prompt appears
5. Dismiss it (before that not what is wanted)
6. Recording lost

**Comment by Sav22999** [comment]
@tuxayo ok, yes. This is because of your display is a bit small (or maybe you have font-size of the system too big). Anyway, you can disable gestures in Settings to fix this inconvenience.
Unluckly I don't know how I can fix this. I'm so sorry you've lost your recording(s)!
